Repository betagouv/mon-service-securise, pull requests merged in 2022-12, with the labels that each got.

#495 [CORRECTION] Jeu des migrations sur les tables `homologations` _et_ `services`
  migrations/20221021094600_suppressionMesuresGeneralesObsoletes.js
  migrations/20221102134033_changeProvenanceService.js
  migrations/20221115150500_suppressionDiffusionRestreinte.js
Labels: bug

#498 Retourne les mesures indispensables avant les recommandées
  src/modeles/mesuresGenerales.js
  test/modeles/mesuresGenerales.spec.js
Labels: enhancement

#500 Supprime AVEC_CORRECTION_ASEPTISATION_MOT_DE_PASSE
  .env.template
  src/mss.js
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
  test/routes/testeurMSS.js
Labels: code

#503 [CORRECTION] Typo dans description
  donneesReferentiel.js
Labels: bug

#501 Restriction de l'affichage des pastilles contributeur
  public/assets/images/pastille_foncee.svg
  public/assets/images/pastille_transparente.svg
  public/assets/images/pastille_violette.svg
  public/assets/styles/espacePersonnel.css
  public/espacePersonnel.js
  public/modules/elementsDom/services.mjs
  test_public/modules/elementsDom/services.spec.mjs
Labels: enhancement

#505 [CORRECTION] Désactivation de l'action quand clic sur une pastille créateur / contributeur
  public/espacePersonnel.js
  public/modules/interactions/pastilles.js
Labels: bug

#506 [Annexe Mesures] Affiche le nombre des mesures « À remplir »
  src/modeles/homologation.js
  src/modeles/statistiquesMesures.js
  src/routes/routesPdf.js
  src/vuesTex/annexeMesures.template.tex
  test/modeles/homologation.spec.js
  test/modeles/statistiquesMesures.spec.js
Labels: enhancement

#510 Crée et utilise network Docker « mss-network »
  .env.template
  README.md
  docker-compose.yml
Labels: enhancement

#504 [REMANIEMENT] Déplace la création des statistiques
  src/modeles/mesuresGenerales.js
  src/modeles/statistiquesMesures.js
  test/modeles/statistiquesMesures.spec.js
Labels: code

#512 Affiche la barre de progression
  donneesReferentiel.js
  public/assets/styles/etapesDossier.css
  src/referentiel.js
  src/routes/routesHomologation.js
  src/vues/homologation/formulaireEtapier.pug
  test/routes/routesHomologation.spec.js
Labels: enhancement

#513 Annexe risques - risques généraux par niveau
  src/modeles/listeRisques.js
  src/modeles/risqueGeneral.js
  src/modeles/risques.js
  test/modeles/listesRisques.spec.js
  test/modeles/risque.spec.js
  test/modeles/risqueGeneral.spec.js
  test/modeles/risques.spec.js
Labels: enhancement

#499 Changement wording contacts utiles
  src/vues/homologation/rolesResponsabilites.pug
Labels: enhancement

#514 Annexe risques - risques spécifiques par niveau
  src/modeles/risques.js
  test/modeles/risques.spec.js
Labels: enhancement

#525 Étape 2 du parcours homologation (« Date »)
  donneesReferentiel.js
  public/assets/styles/etapesDossier.css
  public/assets/styles/formulaire.css
  public/assets/styles/modules/validation.css
  public/assets/styles/utilisateur.css
  public/homologation/etapesDossier.js
  src/vues/fragments/formulaireUtilisateur.pug
  src/vues/homologation/dossiers.pug
  src/vues/homologation/etapeDossier/1.pug
  src/vues/homologation/etapeDossier/2.pug
  src/vues/homologation/etapeDossier/3.pug
Labels: enhancement

#526 Applique le nouveau logo MonServiceSécurisé en entête
  public/assets/images/logo_mss.svg
  public/assets/styles/entete.css
  public/assets/styles/syntheseSecurite.css
  src/vues/homologation/syntheseSecurite.pug
  src/vues/mss.pug
Labels: enhancement

#528 Annexe risques - les commentaires alignés
  src/vuesTex/annexeRisques.template.tex
Labels: enhancement

#533 Ajoute option durée validité 3 ans
  donneesReferentiel.js
Labels: reviewed

#537 [CORRECTION]Échappement des sauts de ligne pour génération des fichiers LaTeX
  src/latex/miseEnFormeDonnees.js
  test/latex/miseEnFormeDonnees.spec.js
Labels: bug

#546 Changement d'adresse de contact
  src/vues/activation.pug
Labels: enhancement

#540 Ordonne les statuts dans l'ordre attendu
  src/modeles/mesure.js
  src/modeles/mesuresGenerales.js
  src/modeles/mesuresSpecifiques.js
  test/modeles/mesure.spec.js
  test/modeles/mesuresGenerales.spec.js
  test/modeles/mesuresSpecifiques.spec.js
Labels: enhancement

#550 [CORRECTION] Tout le bouton « Retour à la synthèse » est cliquable
  public/assets/styles/etapesDossier.css
  src/vues/homologation/formulaireEtapier.pug
Labels: bug

#549 MAJ des CGU
  src/vues/cgu.pug
Labels: enhancement

#553 [REMANIEMENT] Utilise autorisations pour trouver homologations d'un créateur
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: code

#554 Exige présence identifiant service
  consoleAdministration.js
  src/depots/depotDonneesHomologations.js
  src/modeles/journalMSS/erreurs.js
  src/modeles/journalMSS/evenements.js
  test/modeles/journalMSS/evenements.spec.js
Labels: enhancement

#558 MAJ de la FAQ
  src/vues/questionsFrequentes.pug
Labels: enhancement

#562 Ajoute le lien vers les nouvelles annexes et conserve l'ancien en encart
  public/assets/styles/homologation/synthese.css
  src/vues/homologation/synthese.pug
Labels: enhancement

#557 [CORRECTION] Ajout intervenants aux homologations dans script export événements
  src/adaptateurs/adaptateurPostgres.js
Labels: bug

#564 Correction des camemberts des mesures non pleins
  public/scripts/statistiquesMesures.js
Labels: enhancement

#567 Revert "Correction des camemberts des mesures non pleins"
  public/scripts/statistiquesMesures.js
Labels: urgent

#570 🎨 Ajoute lien vers actu ANSSI sur la page d'accueil
  public/assets/styles/index.css
  src/vues/index.pug
Labels: enhancement

#563 Correction du bug des mesures générales indispensables
  src/modeles/homologation.js
  src/modeles/mesureGenerale.js
  src/modeles/mesuresGenerales.js
  test/modeles/homologation.spec.js
  test/modeles/mesureGenerale.spec.js
  test/modeles/mesuresGenerales.spec.js
Labels: bug

#569 Correction des camemberts des mesures non pleins
  public/scripts/statistiquesMesures.js
Labels: enhancement

#579 Montée des versions des dépendances
  package-lock.json
  package.json
Labels: dependencies

#575 Intégration Matomo
  .eslintrc.js
  public/scripts/matomo.js
  src/routes/routesBibliotheques.js
  src/vues/base.pug
Labels: enhancement

#576 Validation pour les cases à cocher
  public/modules/interactions/brancheValidationCasesACocher.mjs
  test_public/modules/interactions/brancheValidationCasesACocher.spec.mjs
Labels: enhancement

#577 Ajoute la validation des cases à cocher et zone de texte
  public/assets/styles/modules/validation.css
  public/homologation/etapesDossier.js
  public/homologation/mesures.js
  public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
  public/modules/interactions/validation.mjs
Labels: enhancement

#582 Nettoyage nouvelles fonctionnalités
  public/assets/images/captures/nouveautes__collaboration.gif
  public/assets/images/captures/nouveautes__page_synthese.png
  src/vues/nouvellesFonctionnalites.pug
Labels: documentation

#586 Suppression du sous titre
  src/vues/cartes/indiceCyber.pug
Labels: enhancement

#573 Champs requis pour les mesures spécifiques coté serveur
  src/modeles/mesureSpecifique.js
  src/routes/routesApiHomologation.js
  test/modeles/mesureSpecifique.spec.js
  test/routes/routesApiHomologation.spec.js
Labels: enhancement

#583 Propriétés obligatoires
  src/modeles/base.js
  test/modeles/base.spec.js
Labels: enhancement

#587 [REMANIEMENT] Supprime duplication
  src/modeles/mesureSpecifique.js
  src/routes/routesApiHomologation.js
  test/modeles/mesureSpecifique.spec.js
Labels: code

#589 [PREMANIEMENT] Constructeur description service
  src/referentiel.js
  test/constructeurs/constructeurDescriptionService.js
  test/depots/depotDonneesHomologations.spec.js
Labels: code

#590 [CORRECTION] Gestion exceptions levées à instanciation `DescriptionService`
  src/routes/routesApiHomologation.js
  test/routes/routesApiHomologation.spec.js
Labels: bug
