Repository betagouv/mon-service-securise, pull requests merged in 2022-03, with the labels that each got.

#162 Affichage « prénom / nom » quand le prénom ou le nom n'ont pas été saisis
  src/modeles/utilisateur.js
  test/modeles/utilisateur.spec.js
Labels: enhancement

#163 Affiche en gris les contributeurs qui n'ont pas encore finalisé leur inscription
  public/assets/images/pastille_grise.svg
  public/assets/styles/espacePersonnel.css
  public/modules/elementsDom/homologations.js
Labels: enhancement

#175 Erreur dans la récupération des paramètres de la sécurité du service
  public/homologation/partiesPrenantes.js
Labels: bug

#176 Linter dans les fichiers .mjs
  .eslintrc.js
  public/modules/interactions/brancheOnglets.mjs
  public/modules/soumetsHomologation.mjs
  test_public/modules/interactions/brancheOnglets.spec.mjs
  test_public/modules/parametres.spec.mjs
Labels: code

#184 L'utilisateur peut mettre à jour son profil (prénom et nom)
  public/assets/styles/formulaire.css
  public/entete.js
  src/depotDonnees.js
  src/routes/routesApi.js
  src/vues/utilisateur/edition.pug
  test/depotDonnees.spec.js
  test/routes/routesApi.spec.js
Labels: enhancement

#192 Copie des parties prenantes en roles et responsabilités
  migrations/20220315083635_ecraseRolesResponsabilitesAvecPartiesPrenantes.js
Labels: bug

#195 Détecte les paramètres de fonction déclarés et inutilisés
  .eslintrc.js
  migrations/20211013203941_ajoutColonneRisquesGenerauxAHomologations.js
  migrations/20211021200444_supprimeColonneRisquesDeHomologations.js
  migrations/20211022131727_ajoutColonneMesuresGeneralesAHomologations.js.js
  migrations/20211031201722_supprimeColonneMesuresDeHomologations.js
  migrations/20220110160004_dupliqueInformationsGeneralesDansDescriptionService.js
  migrations/20220118162341_suppressionColonneHomologationsIdUtilisateur.js
  migrations/20220204145444_supprimeInformationsGenerales.js
  migrations/20220216134942_dupliquePartiesPrenantesDansRolesResponsabilites.js
  migrations/20220315083635_ecraseRolesResponsabilitesAvecPartiesPrenantes.js
  src/middleware.js
  src/mss.js
  src/routes/routesHomologation.js
  test/middleware.spec.js
  test/mocks/middleware.js
Labels: code

#206 Le changement des fichiers *.mjs pour relance les tests
  nodemon.json
Labels: code

#202 Envoie mail de notification sur ajout d'un collaborateur existant
  src/adaptateurs/adaptateurMail.js
  src/erreurs.js
  src/routes/routesApi.js
  test/mocks/middleware.js
  test/routes/routesApi.spec.js
Labels: enhancement
