Repository betagouv/mon-service-securise, pull requests merged in 2022-08, with the labels that each got.

#317 Mets à jour statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#318 [CORRECTION] Orthographie correctement « champ » au singulier
  public/modules/interactions/champsRequis.mjs
  src/vues/inscription.pug
  src/vues/mssInscription.pug
  test_public/modules/interactions/champsRequis.spec.mjs
  test_public/modules/parametres.spec.mjs
  test_public/modules/soumetsHomologation.spec.mjs
Labels: bug

#315 Changement de textes dans la page inscription
  src/vues/mssInscription.pug
Labels: enhancement

#319 Changement cible pour le bouton S'inscrire
  src/vues/index.pug
Labels: enhancement

#316 Message de prévention dans inscription
  public/assets/styles/inscription.css
  src/vues/mssInscription.pug
Labels: enhancement

#320 Mise en avant des champs saisis
  public/assets/styles/inscription.css
  public/inscription.js
Labels: enhancement

#322 Renommage du terme « cyberscore » en « indice de sécurité »
  .env.template
  donneesReferentiel.js
  src/modeles/homologation.js
  src/modeles/mesures.js
  src/modeles/statistiquesMesures.js
  src/referentiel.js
  src/vues/homologation.pug
  test/modeles/homologation.spec.js
  test/modeles/mesures.spec.js
  test/modeles/statistiquesMesures.spec.js
  test/referentiel.spec.js
Labels: enhancement

#325 Nouveaux texte dans la page d'activation de compte
  src/vues/activation.pug
Labels: enhancement

#327 Remplacement des apostrophes obliques par des droites
  src/vues/fragments/modaleDescriptionService.pug
  src/vues/homologation/avisExpertCyber.pug
  src/vues/index.pug
  src/vues/mssInscription.pug
  src/vues/nouvellesFonctionnalites.pug
Labels: enhancement

#328 Mets à jour les statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#333 Utilisation modules Node.js installés à la création de l'image
  .dockerignore
  docker-compose.yml
Labels: bug

#334 Mise à jour des statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#331 Ajoute fichier `README.md`
  README.md
Labels: documentation

#335 Nouveau style des cases à cocher non sélectionnées
  public/assets/styles/formulaire.css
  public/assets/styles/palette.css
Labels: enhancement

#338 Mise à jour des statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#337 [CORRECTION] comparaison au type non défini
  public/modules/interactions/champsRequis.mjs
Labels: code

#340 Nettoyage des photos d'illustrations
  public/assets/images/photo_api.png
  public/assets/images/photo_application.png
  public/assets/images/photo_site_internet.png
Labels: code

#339 [CORRECTION] Utilisation systématique du nom « MonServiceSécurisé »
  package-lock.json
  package.json
  server.js
  src/middleware.js
  src/vues/aPropos.pug
  src/vues/cgu.pug
  src/vues/confidentialite.pug
  src/vues/homologation/decision.pug
  src/vues/index.pug
  src/vues/inscription.pug
  src/vues/mss.pug
  src/vues/questionsFrequentes.pug
  src/vues/utilisateur/edition.pug
  test/middleware.spec.js
Labels: bug, documentation

#343 Mise à jour des srtatistiques usage
  public/modules/statistiques/donnees.mjs
Labels: documentation
