Repository betagouv/mon-service-securise, pull requests merged in 2022-10, with the labels that each got.

#378 Clé de localisation des données disponible dans l'homologation
  src/modeles/homologation.js
  src/vues/homologation/decision.pug
  test/modeles/homologation.spec.js
Labels: enhancement

#386 Espace personnel modale d attestation
  public/assets/styles/bouton.css
  public/assets/styles/carteInformations.css
  public/assets/styles/espacePersonnel.css
  public/assets/styles/formulaire.css
  public/assets/styles/modale.css
  public/assets/styles/modules/lienNouvelOnglet.css
  public/assets/styles/palette.css
  public/assets/styles/utilisateur.css
  public/espacePersonnel.js
  public/modules/elementsDom/services.js
  public/modules/interactions/modale.mjs
  public/modules/modaleNouveauService.js
  src/vues/cartes/indiceCyber.pug
  src/vues/espacePersonnel.pug
  src/vues/fragments/lienNouvelOnglet.pug
  src/vues/fragments/modaleDescriptionService.pug
  src/vues/fragments/modaleNouveauService.pug
Labels: enhancement

#395 Page synthèse de sécurité - Bloc Résumé
  public/assets/images/vignette_drapeau_france.svg
  public/assets/styles/palette.css
  public/assets/styles/syntheseSecurite.css
  src/vues/homologation/syntheseSecurite.pug
Labels: enhancement

#396 Affichage des outils complémentaires sur la nouvelle page Synthèse
  public/assets/images/icone_outils.svg
  public/assets/images/icone_outils_graphiques.svg
  public/assets/styles/homologation/synthese.css
  src/vues/homologation/synthese.pug
Labels: enhancement, urgent

#404 Correction faute d'orthographe
  src/vues/homologation/synthese.pug
Labels: enhancement

#405 Reformulation des textes dans la page des questions fréquentes
  src/vues/questionsFrequentes.pug
Labels: enhancement

#408 Pdf synthèse - Affichage zones statistiques par criticité
  public/assets/images/icone_etoile_orange.svg
  public/assets/styles/syntheseSecurite.css
  src/vues/fragments/statistiquesMesures.pug
  src/vues/homologation/syntheseSecurite.pug
Labels: enhancement

#409 Correction - Répare l'ajout d'un contributeur
  public/modules/interactions/saisieContributeur.js
Labels: bug, urgent

#414 Ajoute le camembert des mesures indispensables
  .eslintrc.js
  public/assets/styles/syntheseSecurite.css
  public/scripts/statistiquesMesures.js
  src/routes/routesBibliotheques.js
  src/vues/documentImprimable.pug
  src/vues/fragments/statistiquesMesures.pug
  src/vues/homologation/syntheseSecurite.pug
Labels: enhancement, urgent

#416 [CORRECTION] Convertis l'email en minuscules pour éviter les comptes en doublon
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
Labels: bug, urgent

#413 Affiche les mesures restantes dans le PDF de synthèse
  public/assets/images/forme_fleche_bleue.svg
  public/assets/styles/syntheseSecurite.css
  src/vues/fragments/statistiquesMesures.pug
  src/vues/homologation/syntheseSecurite.pug
Labels: enhancement

#418 Affiche la légende
  public/assets/styles/palette.css
  public/assets/styles/syntheseSecurite.css
  src/vues/homologation/syntheseSecurite.pug
Labels: enhancement, urgent

#419 Ajoute carte avec liens rétro-compatibilité
  public/assets/styles/deuxColonnes.css
  public/assets/styles/homologation/synthese.css
  public/carteInformations.js
  src/vues/carteInformations.pug
  src/vues/homologation/synthese.pug
  src/vues/mss.pug
Labels: enhancement, urgent

#421 Retrait de « etc. »
  donneesReferentiel.js
Labels: bug

#385 MAJ de la page d'accueil
  public/assets/images/capture_ecran_dossier_homologation.png
  public/assets/images/icone_etape_dossier.svg
  public/assets/images/icone_etape_informations.svg
  public/assets/images/icone_etape_mesures.svg
  public/assets/images/icone_etape_niveau_securite.svg
  public/assets/images/icone_etoile.svg
  public/assets/images/icone_gros_livre.svg
  public/assets/images/icone_personnes.svg
  public/assets/images/image_api.svg
  public/assets/images/image_appli_mobile.svg
  public/assets/images/image_guide_homologation.jpg
  public/assets/images/image_site_internet.svg
  public/assets/images/logo_RGPD.svg
  public/assets/images/logo_rgs.svg
  public/assets/styles/index.css
  public/exempleDossierHomologation.pdf
  src/vues/index.pug
Labels: enhancement

#424 Libellé du lien vers la page d'inscription
  src/vues/index.pug
Labels: enhancement

#425 Troncature du titre du service si nécessaire
  public/assets/styles/homologation/synthese.css
  src/vues/homologation/synthese.pug
Labels: enhancement

#426 Homogénéisation de la description de l'indice cyber
  src/vues/cartes/indiceCyber.pug
  src/vues/fragments/descriptionIndiceCyber.pug
  src/vues/homologation/syntheseSecurite.pug
  src/vues/questionsFrequentes.pug
Labels: enhancement

#430 Espace la fin du titre et le bouton de téléchargement
  public/assets/styles/homologation/synthese.css
Labels: enhancement

#431 Mets à jour statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#437 Ajout departements
  donneesReferentielDepartements.js
Labels: enhancement

#440 Nettoyage des codes de région non utilisés
  donneesReferentielDepartements.js
  test/modeles/utilisateur.spec.js
  test/referentiel.spec.js
Labels: code

#442 Utilisation du vocabulaire du système de design de l'État
  src/vues/mssConnexionEnCours.pug
  src/vues/mssDeconnecte.pug
Labels: enhancement

#443 Ajout de « Questions fréquentes » à la page de connexion
  src/vues/mssConnexionEnCours.pug
Labels: enhancement

#444 Utilisation de l'entête de « Connexion » pour l'inscription
  src/vues/mssInscription.pug
Labels: enhancement

#446 Mets à jour statistiques usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#448 [CORRECTION] Affiche correctement logo sous Chrome
  public/assets/styles/entete.css
Labels: bug

#450 Reconfiguration du moteur de règles
  donneesReferentiel.js
Labels: enhancement, urgent

#452 Correction des statistiques en tenant compte des mesures rendues indispensables
  src/modeles/mesuresGenerales.js
  test/modeles/mesuresGenerales.spec.js
Labels: bug, urgent

#454 Correction de la position du bandeau des nouvelles fonctionnalités
  public/assets/styles/mss.css
Labels: bug

#455 Décoration de « Connexion » avec bordure et icône
  public/assets/images/icone_utilisateur.svg
  public/assets/styles/entete.css
Labels: enhancement

#456 Alignement de la Marianne avec le logo ANSSI
  public/assets/styles/entete.css
Labels: enhancement
