Repository betagouv/mon-service-securise, pull requests merged in 2022-11, with the labels that each got.

#458 Le service peut avoir pour provenance un outil existant
  donneesReferentiel.js
Labels: enhancement

#460 Exécution des migrations knex au lancement de l'application en local
  docker-compose.yml
Labels: code

#462 Icônes qui suivent la taille de police
  public/assets/styles/entete.css
Labels: enhancement

#461 Retirer texte et trait en dessous
  public/assets/images/icone_information_bleue.svg
  public/assets/styles/nouvellesFonctionnalites.css
  src/vues/nouvellesFonctionnalites.pug
Labels: enhancement

#466 Ajout textes et icones novembre
  public/assets/styles/nouvellesFonctionnalites.css
  src/vues/nouvellesFonctionnalites.pug
Labels: enhancement

#467 Nouvel adaptateur Sendinblue pour envoi d'e-mails
  .env.template
  src/adaptateurs/adaptateurMailSendinblue.js
Labels: enhancement

#470 Correction de la suppression d'utilisateur
  src/adaptateurs/adaptateurPostgres.js
Labels: bug

#472 Supprime « Diffusion restreinte » des données à caractère personnel
  donneesReferentiel.js
  migrations/20221115150500_suppressionDiffusionRestreinte.js
Labels: enhancement

#475 Revert "Supprime « Diffusion restreinte » des données à caractère personnel"
  donneesReferentiel.js
  migrations/20221115150500_suppressionDiffusionRestreinte.js
Labels: bug

#476 Supprime « Diffusion restreinte » des données à caractère personnel
  donneesReferentiel.js
  migrations/20221115150500_suppressionDiffusionRestreinte.js
Labels: enhancement

#478 Supprime interrupteur AVEC_INDICE_CYBER
  .env.template
  src/vues/homologation.pug
  src/vues/homologation/synthese.pug
Labels: code

#480 Pdf vide de l'annexe des mesures
  server.js
  src/adaptateurs/adaptateurPdfStatique.js
  src/mss.js
  src/routes/routesPdf.js
  test/routes/routesPdf.spec.js
  test/routes/testeurMSS.js
Labels: enhancement

#482 Moteur de modèle pour générer le latex
  package-lock.json
  package.json
  src/adaptateurs/adaptateurPdfLatex.js
  src/latex/fabriquantGabarit.js
  src/routes/routesPdf.js
  src/vuesTex/annexeMesures.template.tex
  test/latex/fabriquantGabarit.spec.js
Labels: enhancement

#487 Toutes les mesures dans le pdf
  src/mss.js
  src/routes/routesPdf.js
  src/vuesTex/annexeMesures.template.tex
  test/routes/routesPdf.spec.js
Labels: enhancement

#488 Mets à jour statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#477 Consigner la création d'homologation dans un journal MSS en mémoire
  .eslintrc.js
  src/depots/depotDonneesHomologations.js
  src/modeles/journalMSS/evenement.js
  src/modeles/journalMSS/evenements.js
  test/depots/depotDonneesHomologations.spec.js
  test/modeles/journalMSS/evenement.spec.js
  test/modeles/journalMSS/evenements.spec.js
Labels: enhancement

#484 [CORRECTION] Le mot de passe est aseptisé par erreur
  .env.template
  src/mss.js
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
  test/routes/testeurMSS.js
Labels: bug

#489 [CORRECTION] Déclaration en double d'une route
  src/mss.js
Labels: code

#490 Route du Pdf de l'annexe des risques
  src/adaptateurs/adaptateurPdfLatex.js
  src/routes/routesPdf.js
  src/vuesTex/annexeRisques.template.tex
  test/routes/routesPdf.spec.js
Labels: enhancement

#491 Parle de « Service » plutôt que « d'Homologation »
  src/depots/depotDonneesHomologations.js
  src/modeles/journalMSS/evenements.js
  test/depots/depotDonneesHomologations.spec.js
  test/modeles/journalMSS/evenements.spec.js
Labels: enhancement

#494 [CORRECTION] Affichage correct des données du profil utilisateur
  src/vues/fragments/formulaireUtilisateur.pug
Labels: bug
