Repository betagouv/mon-service-securise, pull requests merged in 2022-01, with the labels that each got.

#78 [CORRECTION] Supprime avertissement seuil criticité trop élevé dans dossier homologation
  src/modeles/homologation.js
  src/modeles/informationsGenerales.js
  src/vues/homologation/decision.pug
  test/modeles/homologation.spec.js
  test/modeles/informationsGenerales.spec.js
Labels: bug

#81 Corrige une erreur dans les éléments ajoutables
  public/modules/elementsAjoutables.js
Labels: bug

#85 Ajoute lien retour dans vue dossier homologation
  public/assets/styles/decision.css
  src/vues/homologation/decision.pug
Labels: enhancement

#83 Revoie calcul statut saisie avis expert cyber
  src/modeles/avisExpertCyber.js
  test/modeles/avisExpertCyber.spec.js
Labels: enhancement

#103 [CORRECTION] Affiche correctement avis expert dans document homologation
  src/modeles/homologation.js
  src/vues/fragments/diagnostics.pug
Labels: bug

#84 Reformule le mail de finalisation d'inscription
  src/adaptateurs/adaptateurMail.js
Labels: enhancement

#107 Bump versions
  package-lock.json
  package.json
Labels: code

#110 Permets le transfert d'autorisations depuis une console d'administration
  consoleAdministration.js
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depotDonnees.js
  src/erreurs.js
  test/depotDonnees.spec.js
Labels: enhancement
