Repository betagouv/mon-service-securise, pull requests merged in 2022-02, with the labels that each got.

#106 Utilisation de la palette de couleurs dans le code
  public/assets/images/icone_edition_pastille_grise.svg
  public/assets/styles/bouton.css
  public/assets/styles/decision.css
  public/assets/styles/diagnostics.css
  public/assets/styles/documentation.css
  public/assets/styles/entete.css
  public/assets/styles/espacePersonnel.css
  public/assets/styles/formulaire.css
  public/assets/styles/homologation.css
  public/assets/styles/homologation/aide.css
  public/assets/styles/homologation/formulaire.css
  public/assets/styles/homologation/mesures.css
  public/assets/styles/homologation/risques.css
  public/assets/styles/index.css
  public/assets/styles/modale.css
  public/assets/styles/mss.css
  public/assets/styles/palette.css
  public/assets/styles/piedPage.css
  src/vues/homologation/decision.pug
  src/vues/mss.pug
Labels: code

#121 Supprime les valeurs d'exemple pour les acteurs de l'homologation
  src/vues/fragments/inputIdentite.pug
Labels: enhancement

#119 [NETTOYAGE] Suppression du jeu de données historique
  jeuDonnees.js
Labels: code

#130 Revois la disposition de l'entête de la synthèse d'homologation
  public/assets/images/icone_dossier.svg
  public/assets/styles/homologation.css
  src/vues/homologation.pug
Labels: enhancement

#138 Simplifie instanciation par défaut du dépôt de données
  creeUtilisateurDemo.js
  docker-compose.yml
  server.js
  src/adaptateurs/fabriqueAdaptateurPersistance.js
  src/depotDonnees.js
  src/referentiel.js
Labels: code

#143 Correction de la mise à jour du développement fourniture vide
  src/depotDonnees.js
  test/depotDonnees.spec.js
Labels: bug

#156 [NETTOYAGE] Extrais objet fantaisie middleware
  test/mocks/middleware.js
  test/mss.spec.js
Labels: code

#153 Mets à jour texte mail réinitialisation mot de passe
  src/adaptateurs/adaptateurMail.js
Labels: enhancement

#154 Change icône dossier
  public/assets/images/icone_dossier.svg
Labels: enhancement

#160 Affiche correctement les cartes homologation dans Espace Personnel
  public/assets/styles/espacePersonnel.css
Labels: bug
