Repository betagouv/mon-service-securise, pull requests merged in 2022-06, with the labels that each got.

#282 Ajoute statistique pourcentage de créateurs
  public/modules/statistiques/donnees.mjs
  public/statistiques.js
  src/vues/statistiques.pug
Labels: enhancement

#281 Les mesures spécifiques en haut et en ordre inverse
  public/assets/styles/homologation/mesures.css
  public/homologation/mesures.js
  public/modules/saisieListeItems.js
  src/vues/homologation/mesures.pug
Labels: enhancement

#287 Publie stats de la semaine
  public/modules/statistiques/donnees.mjs
Labels: documentation

#285 Le pied de page en bas de la page
  public/assets/styles/mss.css
Labels: enhancement

#286 Corrige la taille de l'image d'introduction
  public/assets/styles/index.css
Labels: bug

#293 Mets à jour statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#290 [CORRECTION] Typo dans les notes finales de la décision
  src/vues/homologation/decision.pug
Labels: bug

#294 Supprime graphique de la page des statistiques
  public/modules/statistiques/donnees.mjs
  public/statistiques.js
  src/vues/statistiques.pug
Labels: documentation

#292 Renommage des acteurs de l'homologation en gouvernance
  src/modeles/homologation.js
  src/modeles/rolesResponsabilites.js
  src/vues/homologation/decision.pug
  src/vues/homologation/rolesResponsabilites.pug
  test/modeles/rolesResponsabilites.spec.js
  test_public/modules/interactions/brancheOnglets.spec.mjs
Labels: enhancement
