Repository betagouv/mon-service-securise, pull requests merged in 2022-04, with the labels that each got.

#212 Augmente la taille de la puce informations
  public/assets/styles/homologation/mesures.css
  public/assets/styles/modale.css
Labels: enhancement

#213 [NETTOYAGE] Séparation du dépot de données en plusieurs sous-dépôts
  src/depotDonnees.js
  src/depots/depotDonneesAutorisations.js
  src/depots/depotDonneesHomologations.js
  src/depots/depotDonneesUtilisateurs.js
Labels: code

#222 [CORRECTION] Alignement du 'plus' dans la pastille bleue
  public/assets/images/icone_plus_pastille_bleue.svg
Labels: bug

#223 Affichage correct du texte échappé dans le document d'homologation
  src/vues/homologation/decision.pug
Labels: bug

#224 Affichage correct des descriptions des risques
  public/assets/styles/decision.css
Labels: bug

#225 Mise à jour la liste des nouvelles fonctionnalités
  src/vues/nouvellesFonctionnalites.pug
Labels: enhancement

#226 Correction de l'affichage des risques spécifiques échappés
  src/vues/homologation/decision.pug
Labels: bug

#229 Passage durée de vie du cookie de connexion à une heure
  src/mss.js
Labels: enhancement

#231 Reformulation messages invitation à contribution
  src/adaptateurs/adaptateurMail.js
Labels: enhancement

#227 Favicon dans la page document d'homologation
  src/vues/base.pug
  src/vues/homologation/decision.pug
  src/vues/mss.pug
Labels: bug

#235 [CORRECTION] Ne pas envoyer de mail à un contributeur déjà invité
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
Labels: bug
