Repository betagouv/mon-service-securise, pull requests merged in 2022-09, with the labels that each got.

#348 [NETTOYAGE] Suppression espaces finales superflues
  donneesReferentiel.js
  public/assets/styles/espacePersonnel.css
  public/assets/styles/formulaire.css
  public/assets/styles/modale.css
Labels: code

#350 Icône de danger pour les messages d'erreurs
  public/assets/images/icone_attention_rose.svg
  public/assets/styles/modules/validation.css
Labels: enhancement

#351 Changement erreur nom et prénom
  src/vues/fragments/formulaireUtilisateur.pug
Labels: enhancement

#352 Mise à jour des statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#354 Changes corps du texte page APropos
  src/vues/aPropos.pug
Labels: enhancement

#355 Remplaces texte des e-mails page MentionsLegales
  src/vues/mentionsLegales.pug
Labels: enhancement

#360 Ajoute crédits images dans la page « Mentions Légales »
  src/vues/mentionsLegales.pug
Labels: documentation

#364 Suppression d'espaces superflues en fin de ligne
  src/vues/fragments/formulaireUtilisateur.pug
Labels: code

#367 Mise à jour des statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#362 Un espace supplémentaire entre l'icône et le message d'erreur
  public/assets/styles/modules/validation.css
Labels: enhancement

#365 Affichage des boutons de validation en bas à droite de tous les formulaires
  public/assets/styles/bouton.css
Labels: enhancement

#371 Mise à jour des statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#373 Changement titre et légende de la page
  src/vues/fragments/formulaireDescriptionService.pug
Labels: enhancement

#375 Mise à jour du titre et de la légende de la page mesures de sécurité
  src/vues/homologation/mesures.pug
Labels: enhancement

#383 Ajoute question fréquente sur les services exclus
  src/vues/questionsFrequentes.pug
Labels: documentation

#376 MAJ de la légende de la page risques
  src/vues/homologation/risques.pug
Labels: enhancement

#366 Ajoute une route `/service/:id/homologations`
  public/assets/styles/service/homologations.css
  src/mss.js
  src/routes/routesService.js
  src/vues/service/homologations.pug
  test/routes/routesService.spec.js
Labels: enhancement

#374 Accessibilité de la description du statut de déploiement dans l'homologation
  src/modeles/descriptionService.js
  src/modeles/homologation.js
  src/referentiel.js
  test/modeles/descriptionService.spec.js
  test/modeles/homologation.spec.js
  test/referentiel.spec.js
Labels: enhancement

#379 Nouvelle route pour la synthèse de sécurité
  src/routes/routesHomologation.js
  src/vues/homologation/syntheseSecurite.pug
  test/routes/routesHomologation.spec.js
Labels: enhancement

#381 Correction de l'affichage tronqué de nom de service long
  public/assets/styles/mss.css
Labels: bug
