Repository betagouv/mon-service-securise, pull requests merged in 2023-09, with the labels that each got.

#1060 Change la formulation du label
  src/vues/fragments/formulaireUtilisateur.pug
Labels: enhancement

#1062 [CORRECTION] Affichage de modale sans contenu
  public/modules/modaleNouvellesFonctionnalites.mjs
Labels: bug

#1063 Ajoute la technologie `Svelte`
  .eslintrc.js
  .gitignore
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  svelte/lib/Preuve.svelte
  svelte/lib/preuve.ts
  svelte/lib/vite-env.d.ts
  svelte/svelte.config.js
  svelte/tsconfig.json
  svelte/vite.config.mts
Labels: code

#1067 [CORRECTION] Réinitialise le store au montage du composant
  svelte/lib/gestionContributeurs.store.ts
  svelte/lib/gestionContributeurs.ts
Labels: bug

#1066 [HOTFIX] Utilise l'instruction `@html` pour décoder les données
  svelte/.eslintrc.js
  svelte/lib/LigneContributeur.svelte
  svelte/lib/SuppressionContributeur.svelte
Labels: code

#1072 [CORRECTION] Autorise `-` et `.` dans les adresses emails à inviter
  svelte/lib/ChampAvecSuggestions.svelte
Labels: bug

#1075 Supprime du code mort
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
Labels: code

#1076 Utilise une variable d'environnement pour l'URL de l'API Brevo
  .env.template
  src/adaptateurs/adaptateurMailSendinblue.js
Labels: enhancement

#1077 [CORRECTION] N'affiche pas les contributeurs pendant la création du service
  public/scripts/menuNavigation.js
  src/vues/fragments/menuNavigation.pug
Labels: bug

#1087 [CORRECTION] REGEX pour l'invitation par email des contributeurs
  svelte/lib/ChampAvecSuggestions.svelte
Labels: bug

#1088 Déplace le composant Svelte `GestionContributeurs` dans son répertoire
  svelte/lib/gestionContributeurs/ChampAvecSuggestions.svelte
  svelte/lib/gestionContributeurs/GestionContributeurs.svelte
  svelte/lib/gestionContributeurs/InvitationContributeur.svelte
  svelte/lib/gestionContributeurs/LigneContributeur.svelte
  svelte/lib/gestionContributeurs/SuppressionContributeur.svelte
  svelte/lib/gestionContributeurs/gestionContributeurs.d.ts
  svelte/lib/gestionContributeurs/gestionContributeurs.store.ts
  svelte/lib/gestionContributeurs/gestionContributeurs.ts
  svelte/vite.config.mts
Labels: code

#1100 Ajoute effets `hover` et `active` sur le lien de retour au tableau de bord
  public/assets/styles/deuxColonnes.css
Labels: enhancement

#1101 Rétrécis le logo MSS sur les pages « Service »
  public/assets/styles/deuxColonnes.css
Labels: enhancement

#1103 [CORRECTION] Déplace le titre dans `formulaireEtapier`
  src/vues/service/dossiers.pug
  src/vues/service/formulaireEtapier.pug
Labels: bug
