Repository betagouv/mon-service-securise, pull requests merged in 2023-01, with the labels that each got.

#592 Suppression étoile dans la modale de création de nouveau service
  public/assets/styles/modules/validation.css
  src/vues/fragments/modaleNouveauService.pug
Labels: enhancement

#595 Mise à jour statistiques usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#593 [NETTOYAGE] Renommage des routes homologation
  public/homologation/avisExpertCyber.js
  public/homologation/etapesDossier.js
  public/homologation/mesures.js
  public/homologation/risques.js
  public/homologation/rolesResponsabilites.js
  public/modules/soumetsHomologation.mjs
  src/routes/routesApi.js
  src/routes/routesApiService.js
  test/routes/routesApiService.spec.js
  test_public/modules/soumetsHomologation.spec.mjs
Labels: code

#594 Soumettre le formulaire de connexion sur « Entrée »
  public/connexion.js
  src/vues/connexion.pug
Labels: enhancement

#599 Génère un événement de complétude pour chaque service
  consoleAdministration.js
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depotDonnees.js
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: enhancement

#601 Revert "Génère un événement de complétude pour chaque service"
  consoleAdministration.js
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depotDonnees.js
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: code

#597 Ajout des nouvelles fonctionnalités
  src/vues/nouvellesFonctionnalites.pug
Labels: enhancement

#598 Mention champ obligatoire dans les mesures
  public/assets/styles/homologation/descriptionService.css
  public/assets/styles/modules/validation.css
  public/assets/styles/utilisateur.css
  src/vues/homologation/mesures.pug
Labels: enhancement

#596 Affichage des mesures spécifiques dans les onglets
  public/modules/interactions/brancheFiltresMesures.mjs
  test_public/modules/interactions/brancheFiltresMesures.spec.mjs
Labels: bug

#606 [CORRECTION] Utilise un tableau pour le type du service « Démo »
  creeUtilisateurDemo.js
Labels: bug

#609 Journalisation événement suppression service
  src/depots/depotDonneesHomologations.js
  src/modeles/journalMSS/evenementServiceSupprime.js
  test/depots/depotDonneesHomologations.spec.js
  test/modeles/journalMSS/evenementServiceSupprime.spec.js
Labels: enhancement

#607 Changement de wording
  src/vues/aPropos.pug
Labels: enhancement

#605 Remplacer prenom nom DG ANSSI
  src/vues/mentionsLegales.pug
Labels: enhancement

#610 Paramètrage du « Site ID » de Matomo
  .env.template
  public/scripts/matomo.js
  src/vues/base.pug
Labels: enhancement

#613 Affichage centré du label dans les camemberts
  public/scripts/statistiquesMesures.js
Labels: enhancement

#614 Ajout route `PUT /api/motDePasse`
  src/routes/routesApi.js
  test/mocks/middleware.js
  test/routes/routesApi.spec.js
Labels: enhancement

#615 Factorisation appels changements mot de passe
  src/erreurs.js
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
Labels: code

#616 Macros dans les templates latex
  src/vuesTex/annexeMesures.template.tex
  src/vuesTex/annexeRisques.template.tex
  src/vuesTex/fragments/couleurs.tex
  src/vuesTex/fragments/definitionDocument.tex
  src/vuesTex/macros/boiteGrise.tex
  src/vuesTex/macros/entetePiedPage.tex
Labels: code

#618 Route annexe description
  src/adaptateurs/adaptateurPdfLatex.js
  src/routes/routesPdf.js
  src/vuesTex/annexeDescription.template.tex
  test/routes/routesPdf.spec.js
Labels: enhancement

#620 Annexe description - entête et pied de page
  src/adaptateurs/adaptateurPdfLatex.js
  src/modeles/homologation.js
  src/modeles/objetsVues/vueAnnexePDFDescription.js
  src/routes/routesPdf.js
  src/vuesTex/annexeDescription.template.tex
  test/modeles/homologation.spec.js
  test/modeles/objetsVues/vueAnnexePDFDescription.spec.js
  test/routes/routesPdf.spec.js
Labels: enhancement

#621 Correction coquille
  src/vues/fragments/modaleNouveauService.pug
Labels: enhancement

#623 Respecte les normes d'accessibilité
  public/assets/styles/carteInformations.css
Labels: enhancement

#624 Ajout de la page dédiée au changement de mot de passe
  public/motDePasse/edition.js
  src/mss.js
  src/vues/fragments/utilisateur/nouveauMotDePasse.pug
  src/vues/motDePasse/edition.pug
  src/vues/utilisateur/edition.pug
  test/mss.spec.js
Labels: enhancement

#626 [NETTOYAGE] Suppression des espaces en fin de ligne
  public/assets/styles/entete.responsive.css
  public/assets/styles/piedPage.responsive.css
  src/adaptateurs/adaptateurMailSendinblue.js
  src/adaptateurs/adaptateurMailSmtp.js
  src/vues/cgu.pug
  src/vues/mentionsLegales.pug
  src/vuesTex/annexeDescription.template.tex
  src/vuesTex/images/etoile.pdf_tex
  src/vuesTex/images/point-median.pdf_tex
Labels: code

#622 Ajoute les fonctionnalités à l'annexe description
  src/modeles/homologation.js
  src/modeles/itemsAvecDescription.js
  src/modeles/objetsVues/vueAnnexePDFDescription.js
  src/referentiel.js
  src/vuesTex/annexeDescription.template.tex
  src/vuesTex/fragments/couleurs.tex
  test/modeles/itemsAvecDescriptions.spec.js
  test/modeles/objetsVues/vueAnnexePDFDescription.spec.js
  test/referentiel.spec.js
Labels: enhancement

#627 [CORRECTION] Affichage icône nouvel onglet en bleu
  public/assets/styles/homologation/synthese.css
Labels: bug

#630 [CORRECTION] Retourne à espacement vertical connu
  public/assets/styles/mss.css
  src/vues/connexion.pug
Labels: bug

#629 Données stockées à l'annexe description
  src/modeles/objetsVues/vueAnnexePDFDescription.js
  src/referentiel.js
  src/vuesTex/annexeDescription.template.tex
  test/modeles/objetsVues/vueAnnexePDFDescription.spec.js
  test/referentiel.spec.js
Labels: enhancement

#631 Durée maximale acceptable dans l'annexe description
  src/modeles/objetsVues/vueAnnexePDFDescription.js
  src/referentiel.js
  src/vuesTex/annexeDescription.template.tex
  src/vuesTex/macros/boiteGrise.tex
  test/modeles/objetsVues/vueAnnexePDFDescription.spec.js
  test/referentiel.spec.js
Labels: enhancement

#632 Annexe description dans les annexes
  src/adaptateurs/adaptateurPdfLatex.js
  src/routes/routesPdf.js
Labels: enhancement

#633 Nettoyage route pdf annexe description
  src/adaptateurs/adaptateurPdfLatex.js
  src/routes/routesPdf.js
  test/routes/routesPdf.spec.js
Labels: code

#634 Nouvelle route de suppression de service
  src/modeles/autorisations/autorisationBase.js
  src/modeles/autorisations/autorisationCreateur.js
  src/routes/routesApiService.js
  test/modeles/autorisations/autorisationBase.spec.js
  test/modeles/autorisations/autorisationCreateur.spec.js
  test/routes/routesApiService.spec.js
Labels: enhancement

#637 MAJ définition de l'indice cyber
  src/vues/cgu.pug
  src/vues/fragments/descriptionIndiceCyber.pug
Labels: enhancement

#642 PDF d'homologation avec champs éditables
  public/assets/pdf/dossierDecision.pdf
Labels: enhancement

#643 Ajoute lien vers changement mot de passe
  public/assets/styles/entete.css
  public/entete.js
Labels: enhancement

#644 Redirige vers page « Mot de passe » pour accepter les CGU
  src/middleware.js
  test/middleware.spec.js
Labels: enhancement

#640 Menu contextuel de suppression de service
  public/assets/images/icone_poubelle.svg
  public/assets/images/points_horizontal.svg
  public/assets/styles/espacePersonnel.css
  public/assets/styles/modale.css
  public/espacePersonnel.js
  public/modules/elementsDom/services.mjs
  public/modules/interactions/brancheMenuContextuelService.js
Labels: enhancement

#647 Utilisation de la page de changement de MDP pour l'initialisation du mot de passe
  src/mss.js
Labels: enhancement

#649 [CORRECTION] Ne supprime que les contributions d'un utilisateur donné
  src/adaptateurs/adaptateurPersistanceMemoire.js
  test/depots/depotDonneesUtilisateurs.spec.js
Labels: bug

#650 [REMANIEMENT] Regroupement du code lié à HTTP
  server.js
  src/http/configurationServeur.js
  src/http/middleware.js
  src/http/validationMotDePasse.js
  src/mss.js
  src/routes/routesApi.js
  test/http/middleware.spec.js
  test/http/validationMotDePasse.spec.js
Labels: code

#653 Modification d'une coquille
  donneesReferentiel.js
Labels: enhancement

#646 Positionne une carte indiquant le statut d'homologation
  public/assets/images/icone_ko_pastille_rose.svg
  public/assets/styles/carteInformations.css
  public/assets/styles/palette.css
  src/modeles/dossier.js
  src/modeles/dossiers.js
  src/vues/homologation/synthese.pug
  test/modeles/dossier.spec.js
  test/modeles/dossiers.spec.js
Labels: enhancement

#655 [CORRECTION] gestion des transferts
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depots/depotDonneesAutorisations.js
  src/erreurs.js
  test/depots/depotDonneesAutorisations.spec.js
Labels: bug

#657 Regroupe les différentes requêtes pour transfert dans une même transaction
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depots/depotDonneesAutorisations.js
Labels: enhancement, code
