Repository betagouv/mon-service-securise, pull requests merged in 2023-06, with the labels that each got.

#894 [TDB] Affichage en cas de recherche sans résultats
  public/modules/tableauDeBord/tableauDesServices.mjs
Labels: enhancement

#893 [TDB] Affiche un loader pendant la duplication et la suppression
  public/assets/styles/tableauDeBord.css
  public/modules/tableauDeBord/gestionnaireActionsTiroir.mjs
  src/vues/tableauDeBord.pug
Labels: enhancement

#895 Enlève le tri sur la colonne « Homologation »
  public/assets/styles/tableauDeBord.css
  src/vues/tableauDeBord.pug
Labels: enhancement

#896 [REMANIEMENT] Extrais les actions dans des fichiers dédiés
  public/modules/tableauDeBord/actions/ActionContributeurs.mjs
  public/modules/tableauDeBord/actions/ActionDuplication.mjs
  public/modules/tableauDeBord/actions/ActionExport.mjs
  public/modules/tableauDeBord/actions/ActionInvitation.mjs
  public/modules/tableauDeBord/actions/ActionInvitationConfirmation.mjs
  public/modules/tableauDeBord/actions/ActionSuppression.mjs
  public/modules/tableauDeBord/actions/ActionTelechargement.mjs
  public/modules/tableauDeBord/gestionnaireActionsTiroir.mjs
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
  public/modules/tableauDeBord/gestionnaireTiroir.mjs
Labels: code

#897 Efface la sélection des services au moment d'un filtrage
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
  public/modules/tableauDeBord/tableauDesServices.mjs
  src/vues/tableauDeBord.pug
Labels: bug

#898 Conditionne l'affichage des outils en fonction de la selection
  public/modules/tableauDeBord/actions/ActionContributeurs.mjs
  public/modules/tableauDeBord/actions/ActionDuplication.mjs
  public/modules/tableauDeBord/actions/ActionExport.mjs
  public/modules/tableauDeBord/actions/ActionInvitation.mjs
  public/modules/tableauDeBord/actions/ActionInvitationConfirmation.mjs
  public/modules/tableauDeBord/actions/ActionSuppression.mjs
  public/modules/tableauDeBord/actions/ActionTelechargement.mjs
  public/modules/tableauDeBord/gestionnaireBarreOutils.mjs
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
  public/modules/tableauDeBord/gestionnaireTiroir.mjs
  public/modules/tableauDeBord/registreActions.mjs
  public/modules/tableauDeBord/tableauDesServices.mjs
  src/vues/tableauDeBord.pug
Labels: enhancement

#900 [CORRECTION] Ajoute le curseur 'pointer' sur toutes les checkbox
  public/assets/styles/formulaire.css
  public/assets/styles/tableauDeBord.css
Labels: bug

#901 [CORRECTION] Empêche la soumission des formulaires dans le tiroir des actions
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
Labels: bug

#903 [CORRECTION] Affiche une erreur si la personne est déjà invitée
  public/modules/tableauDeBord/actions/ActionInvitation.mjs
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
  src/vues/tableauDeBord.pug
Labels: bug

#908 Update nouvellesFonctionnalites.pug
  src/vues/nouvellesFonctionnalites.pug
Labels: enhancement

#910 Modifie le wording du bandeau d'inscription
  src/vues/mssInscription.pug
Labels: enhancement

#917 [CORRECTION] Utilise le champs `properties` au lieu du champ `eventdata`
  src/adaptateurs/adaptateurTrackingSendinblue.js
Labels: bug

#922 Renomme le titre de la page tableau de bord
  src/vues/tableauDeBord.pug
Labels: enhancement

#929 [REMANIEMENT] Extraction constructeurs test
  .env.template
  test/constructeurs/constructeurAdaptateurPersistanceMemoire.js
  test/constructeurs/constructeurDepotDonneesServices.js
  test/depots/depotDonneesHomologations.spec.js
Labels: code, reviewed

#933 Corrige les données réferentiel
  donneesReferentiel.js
Labels: bug

#934 Renomme les fonctions de hachage utilisant `bcrypt`
  src/adaptateurs/adaptateurChiffrement.js
  src/depots/depotDonneesUtilisateurs.js
  test/depots/depotDonneesUtilisateurs.spec.js
  test/mocks/adaptateurChiffrement.js
Labels: code

#939 [Carrousel] Déploie la nouvelle fonctionnalité du tableau de bord
  donneesReferentiel.js
Labels: enhancement

#941 [Carrousel] Ajoute un bouton pour afficher une nouvelle fonctionnalité dans la page dédiée
  public/assets/styles/nouvellesFonctionnalites.css
  public/nouvellesFonctionnalites.js
  src/vues/nouvellesFonctionnalites.pug
Labels: enhancement

#942 [CORRECTION] Ferme le menu flottant de tri de contributeurs
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
Labels: bug

#944 [CORRECTION] Corrige l'appel au constructeur de `ParcoursUtilisateur`
  test/modeles/parcoursUtilisateur.spec.js
Labels: bug

#952 [Tracking Sendingblue] Envoie évenement tracking complétude ajout description service
  src/depots/depotDonneesHomologations.js
  test/constructeurs/constructeurUtilisateur.js
  test/depots/depotDonneesHomologations.spec.js
  test/tracking/constructeurServiceTracking.js
Labels: enhancement

#945 Ajoute la route de suppression d'autorisation
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
Labels: enhancement

#946 Enrichis l'objet get services avec des permissions
  src/modeles/objetsApi/objetGetServices.js
  test/modeles/objetsApi/objetGetServices.spec.js
Labels: enhancement

#953 Update mss.pug
  src/vues/mss.pug
Labels: enhancement

#954 Update mssConnecte.pug
  src/vues/mssConnecte.pug
Labels: enhancement

#955 [BOM] Suppression de "Faire une suggestion'
  src/vues/mssConnecte.pug
Labels: enhancement

#959 Update mss.pug
  src/vues/mss.pug
Labels: enhancement

#960 Update mssConnecte.pug
  src/vues/mssConnecte.pug
Labels: enhancement

#961 Référence l'URL en `.ssi.gouv.fr`
  .env.template
  src/vues/cgu.pug
Labels: enhancement

#962 [CORRECTION] Affichage de confirmation de suppression contributeur
  public/modules/tableauDeBord/actions/ActionContributeurs.mjs
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
  src/vues/tableauDeBord.pug
Labels: bug

#963 Mentionne la politique de confidentialité lors de l'inscription
  src/vues/fragments/utilisateur/questionCgu.pug
Labels: enhancement

#964 Utilise « Suivant » comme texte du premier bouton
  src/vues/nouvellesFonctionnalites/tableauDeBord.pug
Labels: enhancement

#958 [REMANIEMENT] Passage en `async/await` de `depotDonneesUtilisateurs`
  src/depots/depotDonneesUtilisateurs.js
  test/depots/depotDonneesUtilisateurs.spec.js
Labels: code

#975 [CORRECTION] Corrige 'flotant' en 'flottant'
  public/assets/styles/tableauDeBord.css
  public/modules/tableauDeBord/actions/ActionContributeurs.mjs
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
  src/vues/tableauDeBord.pug
Labels: code

#971 [MIGRATION] Archive les anciens dossiers d'homologations
  migrations/20230627141030_archivageDossiersHomologations.js
  test_migrations/20230627141030_archivageDossiersHomologations.spec.js
Labels: enhancement
