Repository betagouv/mon-service-securise, pull requests merged in 2023-08, with the labels that each got.

#1037 Crée une méthode de fabrication de l'adaptateur Tracking Mémoire
  src/adaptateurs/adaptateurTrackingMemoire.js
  src/adaptateurs/fabriqueAdaptateurTracking.js
  test/constructeurs/constructeurDepotDonneesServices.js
Labels: code

#1040 Force l'acceptation des emails transactionnels au niveau du dépôt
  src/depots/depotDonneesUtilisateurs.js
  test/depots/depotDonneesUtilisateurs.spec.js
Labels: bug

#1041 Renomme la fonction de fabrication du service de Tracking
  src/depots/depotDonneesHomologations.js
  src/modeles/autorisations/ajoutContributeurSurService.js
  src/tracking/serviceTracking.js
  test/constructeurs/constructeurDepotDonneesServices.js
  test/tracking/serviceTracking.spec.js
Labels: code

#1044 [CORRECTION] Effacer l'éventuelle pagination existante
  public/modules/modaleNouvellesFonctionnalites.mjs
Labels: bug

#1047 Permets d'ajouter un contributeur sur plusieurs services à la fois
  src/modeles/autorisations/ajoutContributeurSurServices.js
  test/modeles/autorisations/ajoutContributeurSurServices.spec.js
Labels: enhancement

#1048 Rends disponible l'action « Inviter » lorsque plusieurs services sont sélectionnés
  public/modules/tableauDeBord/actions/ActionInvitation.mjs
  src/routes/privees/routesApiPrivee.js
  test/routes/privees/routesApiPrivee.spec.js
Labels: enhancement

#1054 [HOTFIX] Rajoute l'icone de téléchargement des PDFs
  public/assets/images/icone_telechargement_pdf.svg
Labels: bug

#1042 Suppression de la page d'accueil du service
  public/assets/images/icone_cadenas.svg
  public/assets/images/icone_feuille_papier.svg
  public/assets/images/icone_outils.svg
  public/assets/images/icone_outils_graphiques.svg
  public/assets/images/icone_stylo.svg
  public/assets/styles/homologation/synthese.css
  src/vues/service/synthese.pug
Labels: code

#1053 [FIX] Destinataire du tracking INVITATION_CONTRIBUTEUR
  src/modeles/autorisations/ajoutContributeurSurServices.js
  test/modeles/autorisations/ajoutContributeurSurServices.spec.js
Labels: bug

#1056 Ajoute une couche 'service' au dessus de l'annuaire recherche entreprise
  server.js
  src/adaptateurs/adaptateurRechercheEntrepriseAPI.js
  src/annuaire/serviceAnnuaire.js
  src/mss.js
  src/routes/publiques/routesApiPublique.js
  test/routes/publiques/routesApiPublique.spec.js
  test/routes/testeurMSS.js
Labels: code
