Repository betagouv/mon-service-securise, pull requests merged in 2023-03, with the labels that each got.

#722 Enregistrement sticky des mesures
  public/assets/styles/homologation/mesures.css
  src/vues/service/mesures.pug
Labels: enhancement

#723 Correction position bouton collant des mesures
  public/assets/styles/homologation/mesures.css
Labels: bug

#728 [CORRECTION] Masque une bordure inférieure qui ne doit pas être présente
  public/assets/styles/etapesDossier.css
  src/vues/service/etapeDossier/autorite.pug
Labels: bug

#725 Sous-titre informatif au champ téléphone
  public/assets/styles/utilisateur.css
  src/vues/fragments/formulaireUtilisateur.pug
Labels: enhancement

#729 Supprime un test qui logue une exception dans la console
  test/routes/routesApiService.spec.js
Labels: code

#730 Déplace le bouton « Ajouter une mesure spécifique » à côté de « Enregistrer »
  public/assets/styles/bouton.css
  public/assets/styles/homologation/mesures.css
  src/vues/service/mesures.pug
Labels: enhancement

#732 Raccourcis la phrase de recommandation ANSSI
  donneesReferentiel.js
Labels: enhancement

#734 Déplace du code qui utilise LaTeX
  src/adaptateurs/adaptateurPdfLatex.js
  src/pdf/latex/fabriquantGabarit.js
  src/pdf/latex/miseEnFormeDonnees.js
  test/pdf/latex/fabriquantGabarit.spec.js
  test/pdf/latex/miseEnFormeDonnees.spec.js
Labels: code

#740 Ajoute annexe mesures
  src/adaptateurs/adaptateurPdfHtml.js
  src/pdf/modeles/annexeDescription.pug
  src/pdf/modeles/annexeMesures.pug
  src/pdf/modeles/annexes.pug
  src/pdf/modeles/ressources/images.css
  src/pdf/modeles/ressources/styles.css
  src/routes/routesApiServicePdf.js
Labels: enhancement

#741 Affichage des caractères spéciaux dans l'annexe html des mesures
  src/pdf/modeles/annexeMesures.pug
Labels: bug

#742 Affichage des caractères spéciaux dans l'annexe html de description
  src/pdf/modeles/annexeDescription.pug
Labels: bug

#744 Modification des annexes html pour le saut de page
  src/pdf/modeles/annexeDescription.pug
  src/pdf/modeles/annexeMesures.pug
  src/pdf/modeles/annexeRisques.pug
  src/pdf/modeles/annexes.pug
  src/pdf/modeles/ressources/styles.css
Labels: enhancement, code

#745 Mesures et risques avec commentaires indivisible
  src/pdf/modeles/annexeMesures.pug
  src/pdf/modeles/annexeRisques.pug
Labels: enhancement

#749 [CORRECTION] Supprime le « s » en trop
  src/vues/fragments/modaleNouveauService.pug
Labels: bug

#750 [CONTOURNEMENT] Ne génère pas d'annexe « risques » s'il n'y a aucun risque
  src/adaptateurs/adaptateurPdf.js
Labels: bug

#755 Enlève le saut d'affichage lors de l'apparition d'une modale
  public/assets/styles/modale.css
Labels: bug

#753 Nettoie les variables DKIM obsolètes
  .env.template
Labels: code

#756 Conditionne le rendu de la page d'erreur
  src/mss.js
Labels: bug, code

#758 Affiche une erreur en cas d'invitation déjà envoyée
  public/modules/elementsDom/services.mjs
  public/modules/interactions/saisieContributeur.js
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
Labels: enhancement

#759 Erreur typographique au mot statuts
  donneesReferentiel.js
  src/referentiel.js
  test/modeles/avis.spec.js
  test/modeles/dossier.spec.js
  test/modeles/dossiers.spec.js
  test/modeles/etapes/etapeAvis.spec.js
  test/modeles/homologation.spec.js
  test/referentiel.spec.js
  test/routes/routesApiService.spec.js
Labels: code

#757 Page étape avis sans possibilité d'ajouter des éléments
  public/assets/styles/etapesDossier/avis.css
  src/referentiel.js
  src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
  src/vues/service/etapeDossier/avis.pug
  test/referentiel.spec.js
Labels: enhancement

#763 Marque les événements générés par un administrateur
  consoleAdministration.js
Labels: enhancement

#764 Extrais la dépendences avec le corps du PDF
  src/pdf/modeles/annexe.piedpage.pug
  src/pdf/modeles/annexeDescription.entete.pug
  src/pdf/modeles/annexeMesures.entete.pug
  src/pdf/modeles/annexeRisques.entete.pug
  src/pdf/modeles/base.entete.pug
  src/pdf/modeles/base.pug
  src/pdf/modeles/ressources/piedpage.css
  src/pdf/modeles/ressources/tourDePage.css
Labels: code

#767 Documente les nouvelles fonctionnalités de mars 2023
  src/vues/nouvellesFonctionnalites.pug
Labels: enhancement

#762 Permets la soumissions du formulaire des avis
  public/homologation/etapesDossier.js
  public/modules/soumissionEtapeAvis.mjs
  test_public/modules/soumissionEtapeAvis.spec.mjs
Labels: enhancement

#765 Refacto de la soumission des étape
  public/homologation/etapes/autorite.js
  public/homologation/etapes/avis.js
  public/homologation/etapes/decision.js
  public/homologation/etapes/dossiers.js
  public/homologation/etapes/etapeDate.js
  public/homologation/etapes/formulaireEtape.js
  public/homologation/etapes/recapitulatif.js
  public/homologation/etapesDossier.js
  public/modules/arrangeParametresAvis.mjs
  src/vues/service/dossiers.pug
  src/vues/service/etapeDossier/autorite.pug
  src/vues/service/etapeDossier/date.pug
  src/vues/service/etapeDossier/recapitulatif.pug
  src/vues/service/formulaireEtapier.pug
  test_public/modules/arrangeParametresAvis.spec.mjs
Labels: code

#777 [CORRECTION] Corrige l'url des nouvelles fonctionnalités
  src/vues/mssConnecte.pug
Labels: bug

#774 Considère que l'étape « Avis » est complète s'il n'y a aucun avis
  src/modeles/etapes/etapeAvis.js
  test/modeles/etapes/etapeAvis.spec.js
Labels: enhancement

#778 Supprime le lien vers `Questions fréquentes`
  src/vues/mssConnexionEnCours.pug
  src/vues/mssDeconnecte.pug
Labels: code

#780 Affichage des étiquettes collaborateurs au dessus de la barre collante
  public/assets/styles/homologation/formulaire.css
Labels: bug

#781 Recommandation de l'ANSSI dans la page avis
  src/vues/service/etapeDossier/avis.pug
Labels: enhancement

#782 Boutons radio pour la saisie des avis
  public/assets/styles/homologation/formulaire.css
  public/homologation/etapes/avis.js
  src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
  src/vues/service/etapeDossier/avis.pug
Labels: enhancement

#771 Activation etape avis
  donneesReferentiel.js
  src/modeles/dossier.js
  test/modeles/dossier.spec.js
Labels: enhancement

#786 Coche le bouton radio « Aucun avis » lors de la suppression du dernier avis
  public/homologation/etapes/avis.js
  public/modules/saisieListeItems.js
Labels: enhancement

#794 [CORRECTION] Affiche l'identité des contributeurs sans caractères encodés
  src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
Labels: bug

#792 :warning: [ETAPE DOCUMENTS] Activation - A merger en dernier
  donneesReferentiel.js
  src/modeles/dossier.js
  test/modeles/dossier.spec.js
Labels: enhancement

#798 [CORRECTION] Dockerfile linux - Chromium
  Dockerfile
Labels: bug

#800 Ajoute une « organisation responsable » au service de test
  creeUtilisateurDemo.js
Labels: enhancement
