Repository betagouv/mon-service-securise, pull requests merged in 2023-04, with the labels that each got.

#804 Organisation responsable d'un nouveau service préremplie
  src/routes/routesService.js
  test/routes/routesService.spec.js
Labels: enhancement

#806 Recommandation de l'ANSSI dans l'étape autorité
  src/vues/service/etapeDossier/autorite.pug
  src/vues/service/etapeDossier/avis.pug
  src/vues/service/etapeDossier/decision.pug
  src/vues/service/etapeDossier/documents.pug
  src/vues/service/formulaireEtapierRecommandation.pug
Labels: enhancement

#807 Focus après ajout d'une nouvelle mesure spécifique
  public/homologation/mesures.js
Labels: enhancement

#811 [CORRECTION] Affiche la modale par dessus tout le reste
  public/assets/styles/modale.css
Labels: bug

#813 [CORRECTION] Échappe correctement les commentaires d'avis
  src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
Labels: bug

#810 Carte non homologué
  public/assets/images/icone_ko_pastille_rose.svg
  public/assets/images/icone_ok_pastille_verte.svg
  public/assets/styles/carteInformations.css
Labels: enhancement

#815 Update mesures.js
  public/homologation/mesures.js
Labels: enhancement

#819 Changement de l'url de tchat dans le BOM
  src/vues/mss.pug
  src/vues/mssConnecte.pug
Labels: enhancement

#825 [CORRECTION] Affiche les chiffres uniquement si ils existent
  src/pdf/modeles/syntheseSecurite.pug
Labels: bug

#826 Balise open graph avec le nom du site
  src/vues/base.pug
Labels: enhancement

#830 [CORRECTION] Angles de 360 degré maximum pour les camemberts
  src/pdf/graphiques/camembert.js
  test/pdf/graphiques/camembert.spec.js
Labels: bug

#835 Typographies Marianne de taille moyenne
  public/assets/fonts/Marianne-Medium.woff
  public/assets/fonts/Marianne-Medium.woff2
  public/assets/fonts/Marianne-Medium_Italic.woff
  public/assets/fonts/Marianne-Medium_Italic.woff2
  public/assets/styles/fonts.css
Labels: enhancement

#841 Remplace le bouton "Ajouter" de l'étape document
  src/vues/service/etapeDossier/documents.pug
Labels: enhancement

#839 [TDB] Actions multiples sur les services
  public/assets/images/fleche_pointe_droite.svg
  public/assets/images/icone_ajout_contributeur.svg
  public/assets/images/icone_dupliquer_service.svg
  public/assets/images/icone_supprimer.svg
  public/assets/styles/tableauDeBord.css
  public/tableauDeBord.js
  src/vues/tableauDeBord.pug
Labels: enhancement, pending

#846 Création du contact dans SendinBlue à l'inscription
  src/adaptateurs/adaptateurMailSendinblue.js
  src/adaptateurs/adaptateurMailSurConsole.js
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
Labels: enhancement

#769 [Newsletter] Mise à jour de la politique de confidentialité
  src/vues/confidentialite.pug
Labels: enhancement, pending

#848 [CORRECTION] Force l'acceptation de l'infolettre à `false` lors d'une invitation
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
Labels: code
