Repository betagouv/mon-service-securise, pull requests merged in 2023-02, with the labels that each got.

#659 Correction d'un oubli de suite dans la route delete service
  src/routes/routesApiService.js
Labels: code

#664 Génère un événement de complétude pour chaque service
  consoleAdministration.js
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depotDonnees.js
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: enhancement

#666 [CORRECTION] Ignore les mesures dont le statut n'est pas renseigné
  src/modeles/mesures.js
  test/modeles/mesures.spec.js
Labels: bug

#665 Revert "Génère un événement de complétude pour chaque service"
  consoleAdministration.js
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depotDonnees.js
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: code

#663 Utilisation d'un objet de persistance homologation
  src/adaptateurs/adaptateurPostgres.js
  src/depots/depotDonneesHomologations.js
  src/modeles/base.js
  src/modeles/homologation.js
  src/modeles/listeItems.js
  src/modeles/objetsDonnees/donneesPersistanceHomologation.js
  src/modeles/risqueGeneral.js
  test/modeles/homologation.spec.js
  test/modeles/risqueGeneral.spec.js
Labels: bug, code

#667 Bump version knex
  package-lock.json
  package.json
Labels: dependencies

#668 Affiche toujours les « … » sur fond blanc
  public/assets/styles/espacePersonnel.css
Labels: enhancement

#673 Mets à jour les statistiques d'usage
  public/modules/statistiques/donnees.mjs
Labels: documentation

#661 Route pour duplication de service
  src/routes/routesApiService.js
  test/routes/routesApiService.spec.js
  test/routes/testeurMSS.js
Labels: enhancement

#674 Utilise nom d'homologation disponible pour la duplication
  src/depots/depotDonneesHomologations.js
  src/modeles/homologation.js
  src/routes/routesApiService.js
  test/depots/depotDonneesHomologations.spec.js
  test/modeles/homologation.spec.js
  test/routes/routesApiService.spec.js
Labels: enhancement

#675 Duplication multiple de service
  public/assets/styles/modaleDuplicationService.css
  public/espacePersonnel.js
  src/vues/fragments/modales/modaleDuplicationService.pug
Labels: enhancement

#676 [CORRECTION] Évite les multiples duplications non désirées
  public/espacePersonnel.js
  public/scripts/modaleDuplicationService.js
  src/vues/fragments/modales/modaleDuplicationService.pug
Labels: bug, code

#680 [OPTIMISATION] Réduction de la compléxité algorithmique de duplication de service
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: code

#682 Désactivation du bouton de duplication une fois cliqué
  public/scripts/modaleDuplicationService.js
Labels: enhancement

#681 Montée de version de node en 18
  Dockerfile
  package.json
Labels: dependencies

#683 Retrait l'astérisque de la modale de duplication
  src/vues/fragments/modales/modaleDuplicationService.pug
Labels: enhancement

#686 Génère un événement de complétude pour chaque service
  consoleAdministration.js
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depotDonnees.js
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: enhancement

#688 [CORRECTION] Ramène seulement une fois chaque service à la récupération de tous les services
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
Labels: bug

#690 Montée version de jsdom qui corrige une vulnérabilité
  package-lock.json
  package.json
Labels: dependencies

#692 Duplication test présence homologation
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: code

#684 Bouton du menu contextuel gris quand le menu est ouvert
  public/assets/styles/espacePersonnel.css
  public/modules/interactions/brancheMenuContextuelService.js
Labels: enhancement

#687 Nouveau style pour l'étapier
  public/assets/images/icone_coche_blanche.svg
  public/assets/styles/etapesDossier.css
  src/vues/homologation/formulaireEtapier.pug
Labels: enhancement

#693 Couleurs d'interactions pour l'étapier
  public/assets/styles/etapesDossier.css
  public/assets/styles/palette.css
  src/vues/homologation/formulaireEtapier.pug
Labels: enhancement

#698 Améliore le middleware de test
  test/mocks/middleware.js
  test/routes/routesApi.spec.js
  test/routes/routesApiService.spec.js
  test/routes/testeurMSS.js
Labels: code

#700 MAJ erreur dans le référentiel
  donneesReferentiel.js
Labels: bug

#701 Update formulaireDescriptionService.pug
  src/vues/fragments/formulaireDescriptionService.pug
Labels: enhancement

#704 [CORRECTION] Corrige typo
  src/vues/fragments/descriptionIndiceCyber.pug
Labels: bug, documentation

#702 BOM dans les pages publiques
  public/assets/images/entete_fenetre_bom.svg
  public/assets/images/forme_chevron_blanc.svg
  public/assets/images/icone_croix_blanche.svg
  public/assets/images/icone_croix_bleue.svg
  public/assets/images/vignette_bom.svg
  public/assets/images/vignette_bom_survol.svg
  public/assets/styles/bom.css
  public/scripts/bom.js
  src/vues/mss.pug
  src/vues/mssDeconnecte.pug
Labels: enhancement

#705 Conversion `’` en `'`
  src/vues/cgu.pug
  src/vues/fragments/descriptionIndiceCyber.pug
  src/vues/index.pug
  src/vues/mentionsLegales.pug
  src/vues/nouvellesFonctionnalites.pug
Labels: code

#708 PDF de décision d'homologation avec des IDs de champs précis
  public/assets/pdf/dossierDecision.pdf
Labels: code

#709 Sépare la date du document par un tiret
  public/assets/styles/etapesDossier.css
  src/vues/homologation/etapeDossier/1.pug
Labels: enhancement

#707 Version 2 de CodeQL
  .github/workflows/codeql-analysis.yml
Labels: dependencies, code

#715 Conditionne les logs dans la console du « Journal MSS mémoire »
  .env.template
  src/adaptateurs/adaptateurEnvironnement.js
  src/adaptateurs/adaptateurJournalMSSMemoire.js
Labels: code

#717 Interroge `datesTelechargements` pour savoir si dossier est complet
  src/modeles/dossier.js
  test/modeles/dossier.spec.js
Labels: bug
