Repository betagouv/mon-service-securise, pull requests merged in 2023-12, with the labels that each got.

#1192 Ajoute un point au survol du graphique radar
  public/assets/styles/radarIndiceCyber.css
  src/vues/fragments/indiceCyber/radarIndiceCyber.pug
Labels: enhancement

#1194 Suppression des données obsolètes du référentiel
  donneesReferentiel.js
Labels: enhancement

#1199 Envoie jusqu'à Metabase le nombre d'organisations utilisatrices d'un service
  src/depots/depotDonneesHomologations.js
  src/modeles/journalMSS/erreurs.js
  src/modeles/journalMSS/evenementCompletudeServiceModifiee.js
  test/modeles/journalMSS/constructeurEvenementCompletudeServiceModifiee.js
  test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js
Labels: enhancement

#1201 Supprime la coche blanche sur la valeur de l'indice cyber
  public/assets/images/coche_blanche.svg
  public/assets/styles/homologation/indiceCyber.css
Labels: enhancement

#1203 [CORRECTION] Réparation de l'envoi de complétude à Metabase
  src/depotDonnees.js
  src/depots/depotDonneesHomologations.js
  src/routes/privees/routesApiService.js
  test/depots/depotDonneesHomologations.spec.js
  test/routes/privees/routesApiService.spec.js
Labels: bug

#1207 Diminue le nombre maximum de copie à 10
  src/vues/tiroirs/tiroirDuplication.pug
Labels: enhancement

#1210 [SECURISER] Ajoute un comportement `hover` et `active` sur le cartouche de l'indice cyber
  public/assets/styles/homologation/mesures.css
Labels: enhancement

#1211 [REMANIEMENT] Extrais le composant de 'Fermeture' d'un menu flottant
  svelte/lib/ui/FermetureSurClicEnDehors.svelte
  svelte/lib/ui/MenuFlottant.svelte
Labels: code

#1216 Augmente la taille de la jauge de progression
  public/assets/styles/homologation/mesures.css
  src/vues/fragments/jaugeProgressionMesures.pug
Labels: enhancement

#1217 Reviens au `textarea`
  svelte/lib/directives/validationChamp.ts
  svelte/lib/mesure/Mesure.svelte
Labels: bug

#1221 [SÉCURITÉ] Verification du format de `idReset`
  src/mss.js
  test/mss.spec.js
Labels: code

#1222 Utilise `Enregistré`
  public/service/mesures.js
Labels: enhancement
