Repository betagouv/mon-service-securise, pull requests merged in 2023-05, with the labels that each got.

#850 [Admin] Fonction de suppression de compte
  consoleAdministration.js
Labels: enhancement

#855 [CORRECTION] Corrige un problème d'extraction d'index disponible
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: bug

#856 [CORRECTION] Chaîne proprement les promesses de mise à jour de l'utilisateur
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
Labels: bug

#857 [CORRECTION] Décode les caractères HTML envoyés à Sendinblue
  src/adaptateurs/adaptateurMailSendinblue.js
Labels: bug

#858 Encapsule toutes les actions tiroir dans des formulaires
  public/assets/styles/tableauDeBord.css
  public/modules/tableauDeBord/gestionnaireActionsTirroir.mjs
  public/tableauDeBord.js
  src/vues/tableauDeBord.pug
Labels: code

#859 Corrige la typo de `tirroir` vers `tiroir`
  public/assets/images/fond_entete_tiroir.svg
  public/assets/styles/tableauDeBord.css
  public/modules/tableauDeBord/gestionnaireActionsTiroir.mjs
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
  public/modules/tableauDeBord/gestionnaireTiroir.mjs
  public/tableauDeBord.js
  src/vues/tableauDeBord.pug
Labels: code

#860 Déplace la détection de contact existant dans l'adaptateur
  src/adaptateurs/adaptateurMailSendinblue.js
  src/routes/routesApi.js
  test/routes/routesApi.spec.js
Labels: code

#866 Pointe vers l'étape courante si un dossier d'homologation existe déjà
  src/vues/service/dossiers.pug
Labels: bug

#867 [CORRECTION] Enchaîne correctement les étapes du parcours d'homologation
  donneesReferentiel.js
  src/vues/service/etapeDossier/dateTelechargement.pug
  src/vues/service/etapeDossier/decision.pug
  test/routes/routesService.spec.js
Labels: bug

#871 Déplace les statuts d'homologation
  public/modules/tableauDeBord/tableauDesServices.mjs
  src/adaptateurs/adaptateurCsv.js
  src/modeles/objetsApi/objetGetServices.js
  test/modeles/objetsApi/objetGetServices.spec.js
Labels: code

#874 [CORRECTION] Conserve toujours la pleine largeur des checkboxes
  public/assets/styles/formulaire.css
Labels: bug

#877 Cache bom lorsque le tiroir est ouvert
  public/assets/styles/bom.css
  public/assets/styles/mss.css
  public/modules/tableauDeBord/gestionnaireActionsTiroir.mjs
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
  public/modules/tableauDeBord/gestionnaireTiroir.mjs
  public/scripts/bom.js
Labels: bug

#878 [CORRECTION] Tri correctement en fonction de la direction AUCUNE
  public/modules/tableauDeBord/tableauDesServices.mjs
Labels: bug

#883 Place la barre de recherche sous les informations résumées
  public/assets/styles/tableauDeBord.css
  src/vues/tableauDeBord.pug
Labels: enhancement

#886 Ajoute la note totale dans l'indice cyber
  public/assets/styles/tableauDeBord.css
  public/modules/tableauDeBord/tableauDesServices.mjs
Labels: enhancement

#888 Empêche le focus dans le tiroir si il n'est pas ouvert
  public/assets/styles/tableauDeBord.css
Labels: bug

#889 Amélioration de la position et du scroll du tiroir
  public/assets/styles/tableauDeBord.css
Labels: enhancement
