Repository betagouv/mon-service-securise, pull requests merged in 2023-11, with the labels that each got.

#1162 [CORRECTION] Corrige l'affichage du nombre de contributeurs quand ils sont > 9
  public/assets/styles/menuNavigation.css
Labels: bug

#1165 Extrais la variable de `cache-control` en variable d'environnement
  .env.template
  src/http/configurationServeur.js
  src/mss.js
Labels: code

#1166 Ajoute une page d'erreur en cas d'accès refusé
  public/assets/images/acces_refuse.svg
  public/assets/styles/erreurAccesRefuse.css
  src/http/middleware.js
  src/vues/erreurAccesRefuse.pug
  test/http/middleware.spec.js
Labels: enhancement

#1167 Uniformise les couleurs des `:hover` et `.nom` du menu de droit
  svelte/lib/gestionContributeurs/kit/TagNiveauDroit.svelte
  svelte/lib/gestionContributeurs/personnalisation/TagLectureEcriture.svelte
Labels: code

#1169 Passe en `async/await`
  src/routes/privees/routesApiPrivee.js
Labels: code

#1168 Outillage du dev en local
  README.md
  docker-compose.yml
Labels: code

#1158 Empêche l'utilisateur courant de modifier ses propres autorisations
  src/routes/privees/routesApiService.js
  test/routes/privees/routesApiService.spec.js
Labels: enhancement

#1170 Empêche de modifier une autorisation n'appartenant pas au service ciblé
  src/routes/privees/routesApiService.js
  test/routes/privees/routesApiService.spec.js
Labels: enhancement

#1171 Change le bouton « Presse » de l'accueil
  src/vues/index.pug
Labels: enhancement

#1177 Mise à jour du référentiel de l'indice cyber
  donneesReferentiel.js
  src/referentiel.js
  test/referentiel.spec.js
Labels: enhancement

#1176 Ajoute le type de requête dans l'erreur « Trop de trafic »
  src/adaptateurs/adaptateurProtection.js
Labels: code

#1179 [MIGRATION] Supprime le champ `type` de `autorisations`
  migrations/20231124110131_supprimeTypeAutorisation.js
Labels: code

#1180 [SOIN] Renomme `AutorisationBase` en `Autorisation`
  src/depots/depotDonneesHomologations.js
  src/modeles/autorisations/ajoutContributeurSurServices.js
  src/modeles/autorisations/autorisation.js
  src/modeles/autorisations/fabriqueAutorisation.js
  src/modeles/homologation.js
  src/modeles/objetsApi/objetGetIndicesCyber.js
  src/modeles/objetsApi/objetGetService.js
  src/modeles/objetsApi/objetGetServices.js
  src/routes/privees/routesApiServicePdf.js
  src/routes/privees/routesService.js
  test/constructeurs/constructeurAutorisation.js
  test/modeles/autorisations/autorisation.spec.js
  test/routes/privees/routesApiService.spec.js
Labels: code

#1183 Supprime le lien "Découvrez nos nouveautés" sur la page d'erreur de droit d'accès
  src/vues/erreurAccesRefuse.pug
Labels: enhancement

#1182 Ouvre le bouton "Inviter des contributeurs" pendant 3 secondes à l'ouverture du menu
  public/assets/styles/menuNavigation.css
  public/scripts/menuNavigation.js
  src/vues/fragments/menuNavigation.pug
Labels: enhancement

#1185 Cesse de polluer Sentry avec les erreurs remontées par les bibliothèques distantes
  src/routes/publiques/routesBibliotheques.js
Labels: code

#1187 Ajoute le lien vers la page de l'indice cyber
  public/assets/images/forme_chevron_bleu_fonce.svg
  public/assets/styles/menuNavigation.css
  src/vues/fragments/menuNavigation.pug
Labels: enhancement

#1191 Ajoute un conditionnement pour l'affichage de la durée d'homologation conseillée
  src/vues/service/indiceCyber.pug
Labels: enhancement
