Repository betagouv/mon-service-securise, pull requests merged in 2023-07, with the labels that each got.

#983 [CORRECTION] Compteur de services homologués
  src/modeles/objetsApi/objetGetServices.js
  test/modeles/objetsApi/objetGetServices.spec.js
Labels: bug

#984 Utilise `.ssi` plutôt que `.beta` pour la FAQ
  src/mss.js
  src/vues/cartes/indiceCyber.pug
  src/vues/fragments/modaleNouveauService.pug
  src/vues/mss.pug
  src/vues/mssConnecte.pug
  src/vues/service/etapeDossier/autorite.pug
Labels: enhancement

#986 Déplace un objet API dans le bon répertoire
  src/modeles/objetsApi/objetApiStatutHomologation.js
  src/routes/routesService.js
  test/modeles/objetsApi/objetApiStatutHomologation.spec.js
Labels: code

#987 Renomme l'objet de persistance d'une homologation
  src/modeles/homologation.js
  src/modeles/objetsPersistance/objetPersistanceHomologation.js
  test/modeles/objetsPersistance/objetPersistanceHomologation.spec.js
Labels: code

#988 Renomme et déplace les objets liés à la génération de PDF
  src/modeles/homologation.js
  src/modeles/objetsPDF/objetPDFAnnexeDescription.js
  src/modeles/objetsPDF/objetPDFAnnexeMesures.js
  src/modeles/objetsPDF/objetPDFAnnexeRisques.js
  test/modeles/homologation.spec.js
  test/modeles/objetsPDF/objetPDFAnnexeDescription.spec.js
  test/modeles/objetsPDF/objetPDFAnnexeMesures.spec.js
  test/modeles/objetsPDF/objetPDFAnnexeRisques.spec.js
Labels: code

#997 [CORRECTION] Le champ postes ne doit pas accepter de valeur vide
  public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
Labels: bug

#998 Ajoute la route `/api/desinscriptionInfolettre` dans la liste des endpoints sans CSRF
  src/http/configurationServeur.js
Labels: bug

#1003 [REMANIEMENT] Regroupe les routes publiques dans `/routes/publiques`
  src/http/middleware.js
  src/mss.js
  src/routes/publiques/routesBibliotheques.js
  src/routes/publiques/routesStyles.js
  test/routes/publiques/routesBibliotheques.spec.js
  test/routes/publiques/routesStyles.spec.js
Labels: code

#1004 [REMANIEMENT] Supprime la duplication de code de mapping
  src/routes/mappeur/utilisateur.js
  src/routes/privees/routesApiPrivee.js
  src/routes/publiques/routesApiPublique.js
Labels: code

#1005 [NETTOYAGE] Nettoie la validation de mot de passe
  public/motDePasse/validationMotDePasse.mjs
  src/http/validationMotDePasse.js
  src/routes/privees/routesApiPrivee.js
  test/http/validationMotDePasse.spec.js
  test/routes/privees/routesApiPrivee.spec.js
  test_public/motDePasse/validationMotDePasse.spec.mjs
Labels: code

#1009 [CORRECTION] Le chiffre dans le camembert « À remplir »
  src/modeles/statistiquesMesures.js
  src/pdf/graphiques/camembert.js
  src/pdf/modeles/ressources/styles.css
  src/pdf/modeles/syntheseSecurite.pug
  test/modeles/statistiquesMesures.spec.js
  test/pdf/graphiques/camembert.spec.js
Labels: bug

#1008 Ajoute l'attribut `lang` dans l'HTML de base
  src/vues/base.pug
Labels: enhancement

#1012 Conditionne l'affichage du titre de la page d'édition de mot de passe
  src/vues/motDePasse/edition.pug
Labels: enhancement

#1013 Ajoute un conteneur docker 'Vault' pour gérer le chiffrement
  docker-compose.yml
  scripts/init-mss-crypto.sh
Labels: enhancement

#1016 [CORRECTION] Wording du nom de fichier
  src/routes/privees/routesApiServicePdf.js
  test/routes/privees/routesApiServicePdf.spec.js
Labels: bug

#1017 [CORRECTION] Comptabilise les services bientôt expirés dans les services homologués
  src/modeles/objetsApi/objetGetServices.js
  test/modeles/objetsApi/objetGetServices.spec.js
Labels: bug

#1018 Ajoute un fond et un titre sur la case infolettre
  public/assets/styles/formulaire.css
  src/vues/fragments/formulaireUtilisateur.pug
Labels: enhancement

#1022 Exécute `npm audit fix --force` pour rester à jour
  package-lock.json
  package.json
Labels: code

#1024 Ajoute les inscrits MSS aux destinataires des emails transactionnels de relance
  .env.template
  src/adaptateurs/adaptateurMailSendinblue.js
Labels: enhancement

#1025 Passe les tests en `async/await`
  test/routes/privees/routesApiPrivee.spec.js
Labels: code

#1029 Prends en compte la pagination imposée par l'API Brevo
  consoleAdministration.js
Labels: bug

#1030 [CORRECTION] Utilise explicitement l'adaptateur Tracking mémoire dans les tests
  test/depots/depotDonneesHomologations.spec.js
Labels: bug

#1031 Passage de tests en `async/await`
  test/depots/depotDonneesHomologations.spec.js
Labels: code
