Repository betagouv/mon-service-securise, pull requests merged in 2023-10, with the labels that each got.

#1106 [CORRECTION] Répare l'affichage en cas de bandeau présent
  public/assets/styles/tableauDeBord.css
Labels: bug

#1111 [CORRECTION] Empêche d'inviter la même personne 2 fois
  svelte/lib/gestionContributeurs/ChampAvecSuggestions.svelte
  svelte/lib/gestionContributeurs/InvitationContributeur.svelte
Labels: bug

#1110 Supprime message d'information
  svelte/lib/gestionContributeurs/SuppressionContributeur.svelte
Labels: enhancement

#1114 Affiche « Nouveautés » sur le tableau de bord
  src/vues/motDePasse/edition.pug
  src/vues/tableauDeBord.pug
  src/vues/utilisateur/edition.pug
Labels: enhancement

#1115 Utilise `node 18` pour la CI
  .github/workflows/node.js.yml
Labels: code

#1120 Permets de masquer une rubrique
  svelte/lib/gestionContributeurs/personnalisation/PersonnalisationDroits.svelte
Labels: enhancement

#1125 Change un placeholder
  public/service/descriptionService.js
  src/vues/fragments/formulaireDescriptionService.pug
Labels: enhancement

#1126 Navigation vers « Sécuriser » ou « Décrire »
  public/modules/soumetsHomologation.mjs
  test_public/modules/soumetsHomologation.spec.mjs
Labels: enhancement

#1131 Utilise systématiquement `uneAutorisation` au lieu de données brute
  test/depots/depotDonneesAutorisations.spec.js
Labels: code

#1132 Utilise systématiquement `uneAutorisation` au lieu de données brute
  test/depots/depotDonneesHomologations.spec.js
  test/depots/depotDonneesUtilisateurs.spec.js
Labels: code

#1134 Supprime l'utilisation du type `createur` dans l'adaptateur mémoire
  src/adaptateurs/adaptateurPersistanceMemoire.js
Labels: enhancement

#1135 Utilise systématiquement le constructeur de service dans les tests qi utilise les contributeurs et créateurs
  test/constructeurs/constructeurService.js
  test/modeles/homologation.spec.js
Labels: code

#1136 Modifie le wording de l'item de menu 'Personnalisé'
  svelte/lib/gestionContributeurs/kit/TagNiveauDroit.svelte
Labels: enhancement

#1137 Met à jour les actions Github
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
Labels: dependencies

#1138 [MIGRATION] Ajoute le champ `estProprietaire`
  migrations/20231020062200_ajouteChampEstProprietaire.js
Labels: enhancement

#1139 Change le lien du logo MSS sur le tableau de bord
  src/vues/deuxColonnes.pug
  src/vues/historiqueProduit.pug
  src/vues/motDePasse/edition.pug
  src/vues/nouvellesFonctionnalites/menuNavigation.pug
  src/vues/nouvellesFonctionnalites/tableauDeBord.pug
  src/vues/tableauDeBord.pug
  src/vues/utilisateur/edition.pug
Labels: enhancement

#1140 Utilise `estProprietaire` dans la méthode `homologations`
  src/adaptateurs/adaptateurPostgres.js
Labels: enhancement

#1141 Utilise `estProprietaire` dans la méthode `rechercheContributeurs`
  src/adaptateurs/adaptateurPostgres.js
Labels: enhancement

#1143 Modifie 'Email' en 'Email professionnel' au moment de l'inscription
  src/vues/fragments/formulaireUtilisateur.pug
Labels: enhancement

#1144 Filtre les propriétaires via `estProprietaire` dans l'affichage des autorisations d'un service
  src/routes/privees/routesApiService.js
Labels: enhancement

#1148 Renomme `Createur` en `Proprietaire` dans le constructeur d'autorisation de test
  test/constructeurs/constructeurAutorisation.js
  test/depots/depotDonneesAutorisations.spec.js
  test/depots/depotDonneesHomologations.spec.js
  test/depots/depotDonneesUtilisateurs.spec.js
  test/modeles/autorisations/ajoutContributeurSurServices.spec.js
  test/modeles/objetsApi/objetGetIndicesCyber.spec.js
  test/modeles/objetsApi/objetGetService.spec.js
  test/modeles/objetsApi/objetGetServices.spec.js
  test/routes/privees/routesApiPrivee.spec.js
  test/routes/privees/routesApiService.spec.js
Labels: code

#1151 Nettoyage de fonctions de la console administration
  consoleAdministration.js
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depotDonnees.js
  src/depots/depotDonneesAutorisations.js
  src/depots/depotDonneesHomologations.js
  src/erreurs.js
  test/depots/depotDonneesAutorisations.spec.js
  test/depots/depotDonneesHomologations.spec.js
Labels: code

#1152 Corrige la fonction `ajouteDescriptionServiceAHomologation`
  src/depots/depotDonneesHomologations.js
Labels: bug

#1153 Corrige la fonction `ajouteMesuresAHomologation`
  src/depots/depotDonneesHomologations.js
  src/routes/privees/routesApiService.js
  test/depots/depotDonneesHomologations.spec.js
  test/routes/privees/routesApiService.spec.js
Labels: bug

#1154 Supprime la dépendance à `service.createur` dans la fonction `nouveauService`
  src/depots/depotDonneesHomologations.js
Labels: enhancement, code

#1159 [HOTFIX] Corrige la soumissions des formulaires
  public/service/risques.js
  public/service/rolesResponsabilites.js
Labels: bug
