Repository betagouv/mon-service-securise, pull requests merged in 2024-07, with the labels that each got.

#1574 Temporise la génération d'évènements complétude dans la console d'administration
  consoleAdministration.js
Labels: enhancement

#1576 Amélioration du titre dans la partie décrire
  public/service/descriptionService.js
Labels: enhancement

#1577 [CORRECTION] Évite de laisser toujours visible la pastille des filtres
  svelte/lib/tableauDesMesures/filtres/IconeFiltre.svelte
  svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
Labels: bug

#1579 Supprime le filtre de mesures générales dans homologation
  src/modeles/homologation.js
  test/modeles/homologation.spec.js
Labels: enhancement

#1580 Supprime la mise à jour totale des mesures d'un service
  src/depotDonnees.js
  src/depots/depotDonneesHomologations.js
  src/routes/connecte/routesConnecteApiService.js
  test/depots/depotDonneesHomologations.spec.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1583 Mentionne les mesures partielles dans les explications de l'indice cyber
  src/vues/service/indiceCyber.pug
Labels: enhancement

#1588 [CMS CRISP] Ajoute la classe "CrispMarkdown"
  package-lock.json
  package.json
  src/cms/crispMarkdown.js
  test/cms/crispMarkdown.spec.js
Labels: enhancement

#1594 [HOME] Modifie l'illustration de la première étape de la home
  public/assets/images/home/illustration_etape_1.svg
Labels: enhancement

#1599 [PLAN D'ACTION] Ajoute une icône dans la barre de recherche
  public/assets/images/icone_recherche.svg
  svelte/lib/tableauDesMesures/TableauDesMesures.svelte
Labels: enhancement

#1601 [PLAN D'ACTION] Applique le nouveau style de la sélection de statut de mesure
  svelte/lib/ui/SelectionStatut.svelte
Labels: enhancement

#1604 [PLAN D'ACTION] Ajoute un identifiant numérique à toute les mesures du référentiel
  donneesReferentiel.js
Labels: enhancement

#1606 [PLAN D'ACTION] Corrige l'espacement du titre du tiroir
  public/assets/styles/homologation/mesures.css
Labels: enhancement

#1610 [CORRECTION] Corrige l'affichage des tiroirs de duplication et d'invitation
  public/assets/styles/tiroir.css
Labels: bug

#1609 [SUGGESTIONS D'ACTIONS] Encapsule la suggestion d'action renvoyée par l'API
  public/modules/tableauDeBord/tableauDesServices.mjs
  src/modeles/objetsApi/objetGetService.js
  test/modeles/objetsApi/objetGetService.spec.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1615 Ajoute une route permettant d’acquitter une suggestion d’action
  src/routes/connecte/routesConnecteApiService.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1616 [CORRECTION] Affiche correctement la valeur du nombre d'organisations…
  src/vues/fragments/formulaireDescriptionService.pug
Labels: bug

#1618 [CORRECTION] Ajoute les identifiants numériques à la visite guidée
  svelte/lib/tableauDesMesures/modeVisiteGuidee/donneesVisiteGuidee.ts
Labels: bug

#1619 [CORRECTION] N'affiche pas le toaster si aucune notifications n'est visible
  svelte/lib/ui/Toaster.svelte
Labels: bug

#1622 [CORRECTION] Assigne une valeur par défaut au nombre d’entité
  public/modules/parametresDescriptionService.mjs
  public/service/descriptionService.js
Labels: bug

#1626 [DÉPENDANCES] Met à jour la version de `npm`
  package-lock.json
  package.json
Labels: dependencies

#1631 [CORRECTION] Ajoute le canal de diffusion aux tâches de service et d'utilisateur
  src/notifications/centreNotifications.js
  test/notifications/centreNotifications.spec.js
Labels: bug

#1628 [INVESTIGATION] Ajoute un 'log' dédié dans Sentry pour les erreurs CSRF
  src/adaptateurs/adaptateurGestionErreurSentry.js
Labels: bug, enhancement

#1630 [CORRECTION] Remet le niveau de sécurité précédemment sélectionné
  public/modules/soumetsHomologation.mjs
  public/service/descriptionService.js
Labels: bug, enhancement

#1632 [CENTRE NOTIFICATIONS] Ne pas afficher les tâches de service déjà lues
  src/notifications/centreNotifications.js
  test/notifications/centreNotifications.spec.js
Labels: enhancement

#1633 [Déploiement continu] Démarrage du déploiement via la CI/CD
  .github/workflows/deploiement.yml
Labels: enhancement, code

#1635 [TEMPORAIRE] Masque les liens vers les articles de blog
  svelte/lib/mesure/Mesure.svelte
Labels: bug, code

#1640 [CORRECTION] Impose la sélection d'un statut dans le tiroir de mesure
  svelte/lib/ui/SelectionStatut.svelte
Labels: bug

#1638 [SÉCURISER] Remplace les liens vers le blog par des liens internes
  donneesReferentiel.js
  svelte/lib/mesure/Mesure.svelte
Labels: enhancement

#1647 Changement du nombre d'utilisateurs
  src/vues/home.pug
Labels: enhancement
