Repository betagouv/mon-service-securise, pull requests merged in 2024-11, with the labels that each got.

#1915 [CORRECTION] Corrige un bug sur mise à jour d'une mesure spécifique avec responsable
  src/modeles/service.js
  test/modeles/service.spec.js
Labels: bug

#1917 [CORRECTION] Applique la police "Marianne" sur la liste déroulante
  svelte/lib/ui/ListeDeroulante.svelte
Labels: bug, enhancement

#1925 [CORRECTION] Affiche la modale de reconnexion si une erreur "CSRF mismatch" est interceptée par le front
  public/scripts/csrf.js
Labels: bug

#1928 Mise à jour de home.pug pour refléter le passage à 6 000 utilisateurs
  src/vues/home.pug
Labels: enhancement

#1931 [CORRECTION] Ajoute un accent sur MonServiceSécurisé
  svelte/lib/profil/Profil.svelte
Labels: bug

#1934 [TABLEAU DE BORD] Ajoute le badge du statut d'homologation
  svelte/lib/tableauDeBord/TableauDeBord.svelte
  svelte/lib/tableauDeBord/elementsDeService/EtiquetteHomologation.svelte
Labels: enhancement

#1924 Mise à jour du lien Calendly pour les rendez-vous de présentation
  src/vues/home.pug
Labels: enhancement

#1923 Mise à jour du lien Calendly pour les rendez-vous de présentation
  src/vues/mss.pug
Labels: enhancement

#1922 Mise à jour du lien Calendly pour les rendez-vous de présentation
  src/vues/mssConnecte.pug
Labels: enhancement

#1941 [CORRECTION] Corrige l'alignement du texte sur tout MonServiceSécurisé
  svelte/lib/uiKit/UiKit.svelte
Labels: bug

#1943 [CORRECTION] Aligne tout le contenu du tableau de bord à gauche
  svelte/lib/tableauDeBord/TableauDeBord.svelte
Labels: bug

#1946 [SOIN] Extrais une fonction pour lire les données partagées
  public/accueilInscription.js
  public/connexion-v2.js
  public/creation-compte.js
  public/modules/donneesPartagees.mjs
  public/modules/suggestion/suggestionEntite.js
  public/modules/tableauDeBord/actions/ActionMesure.mjs
  public/modules/tableauDeBord/tableauDesServices.mjs
  public/motDePasse/edition.js
  public/mssConnecte.js
  public/profil.js
  public/scripts/conseilsCyber.js
  public/scripts/csrf.js
  public/scripts/menuNavigation.js
  public/service/descriptionService.js
  public/service/homologation/formulaireEtape.js
  public/service/indiceCyber.js
  public/service/mesures.js
  public/service/risques-v2.js
  public/supervision.js
  public/tableauDeBord-v2.js
Labels: code

#1945 [SOIN] Utilise un 'objet' pour instancier le serveur
  server.js
  src/mss.js
  src/routes/connecte/routesConnecteApi.js
  src/routes/connecte/routesConnecteApiService.js
  src/routes/nonConnecte/routesNonConnecteApi.js
  test/routes/testeurMSS.js
Labels: code

#1944 [SOIN] Supprime les feature flags inutilisés
  .env.template
  src/adaptateurs/adaptateurEnvironnement.js
  src/http/middleware.js
  src/vues/mssConnecte.pug
  test/http/middleware.spec.js
Labels: code
