Repository betagouv/mon-service-securise, pull requests merged in 2024-12, with the labels that each got.

#1950 [CORRECTION] Ajoute un `hover` sur les liens du fil d'ariane
  svelte/lib/ui/FilAriane.svelte
Labels: bug, enhancement

#1952 [TDB] Ajoute les cases à cocher devant les noms de service et le nombre de lignes sélectionnées
  svelte/lib/tableauDeBord/TableauDesServices.svelte
Labels: enhancement

#1958 [CORRECTION] Corrige le controlleur d'erreur utilisé par MSS
  src/mss.ts
Labels: bug

#1957 [CORRECTION] Corrige l'interception des erreurs
  public/scripts/csrf.mjs
Labels: bug

#1954 [TDB] Ajoute le nom de l'organisation responsable
  svelte/lib/tableauDeBord/TableauDesServices.svelte
Labels: enhancement

#1963 [CORRECTION] Utilise un id 'tiroir' pour séparer le Legacy du Svelte
  svelte/lib/tiroir/Tiroir.svelte
Labels: bug

#1966 [TDB] Affiche la page "sans resultat"
  public/assets/images/icone_rafraichir.svg
  svelte/lib/tableauDeBord/TableauDesServices.svelte
  svelte/lib/ui/Bouton.svelte
Labels: enhancement

#1967 [UI Kit] Ajoute un menu de navigation dans l'UI Kit
  svelte/lib/uiKit/UiKit.svelte
Labels: enhancement

#1968 [SOIN] N'affiche le loader qu'au premier affichage de la page
  svelte/lib/tableauDeBord/TableauDeBord.svelte
Labels: enhancement

#1969 Supprime Henri de la home
  public/assets/images/home/henri.webp
  src/vues/home.pug
Labels: enhancement

#1972 [CORRECTION] Demande confirmation à la suppression d'un projet d'homologation
  public/modules/tableauDeBord/actions/ActionSuppressionDossierCourant.mjs
  src/vues/tiroirs/tiroirSuppressionDossierCourant.pug
Labels: enhancement

#1973 [Correction] Retire le challenge mot de passe sur la suppression de dossier
  src/routes/connecte/routesConnecteApiService.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1975 [STATISTIQUES] Mets à jour la valeur de l'évolution de l'indice cyber
  src/adaptateurs/adaptateurStatistiquesMetabase.js
  src/vues/statistiques.pug
Labels: enhancement

#1977 [MonProfilAnssi] Inscris les invités à MonProfilAnssi
  src/depots/depotDonneesUtilisateurs.js
  test/depots/depotDonneesUtilisateurs.spec.js
Labels: enhancement

#1980 [CORRECTION] Utilise la fabrique d'adaptateurProfilAnssi
  server.ts
Labels: bug

#1985 [HOMOLOGUER] Modifications UI de l'encart de projet d'homologation
  public/assets/styles/dossiers.css
  src/vues/service/dossiers.pug
Labels: enhancement
