Repository betagouv/mon-service-securise, pull requests merged in 2024-06, with the labels that each got.

#1506 Ajoute un `sitemap`
  public/assets/fichiers/sitemap.xml
  src/routes/nonConnecte/routesNonConnectePage.js
  test/routes/nonConnecte/routesNonConnectePage.spec.js
Labels: enhancement

#1504 [ADMIN] Permets de transformer une autorisation en « Propriétaire »
  consoleAdministration.js
Labels: enhancement

#1509 [CONSOLE ADMINISTRATION] Suppression du contact dans brevo
  consoleAdministration.js
  src/adaptateurs/adaptateurMailMemoire.js
  src/adaptateurs/adaptateurMailSendinblue.js
Labels: enhancement

#1527 [VISITE GUIDEE] met à jour le message pour le centre de notifications
  svelte/lib/visiteGuidee/etapes/piloter/EtapePiloter.svelte
Labels: enhancement

#1530 [BOM] Modifie le liseré du bouton et de l'encart
  public/assets/styles/bom.css
Labels: enhancement

#1529 Modifie le titre de la modale d'encart homologation
  src/vues/service/modaleEncartHomologation.pug
Labels: enhancement

#1535 [BOM] Égalise les arrondis de la modale et du bandeau de titre
  public/assets/styles/bom.css
Labels: enhancement

#1536 [CORRECTION] Corrige l'affiche du footer dans le parcours service
  public/assets/styles/parcoursService.css
Labels: bug

#1537 [CORRECTION] Corrige l'affiche de la modale sur le bouton de nouvelle homologation
  svelte/lib/visiteGuidee/etapes/homologuer/EtapeHomologuer.svelte
Labels: bug

#1540 [DECRIRE] Affiche le message en cas de doublon de nom
  public/service/descriptionService.js
Labels: bug

#1539 [VISITE GUIDEE] Met à jour les GIF
  public/assets/images/visiteGuidee/bom.gif
  public/assets/images/visiteGuidee/nouveautes.gif
Labels: enhancement

#1538 Ajoute une modale avec une animation lors de la création d'un service
  public/assets/styles/homologation/descriptionService.css
  public/modules/soumetsHomologation.mjs
  src/vues/service/creation.pug
Labels: enhancement

#1543 [BOM] Aligne le titre du BOM à gauche en version mobile
  public/assets/styles/bom.responsive.css
Labels: enhancement

#1544 [NIVEAU DE SÉCURITÉ] Ajoute une méthode permettant d'estimer le niveau de sécurité
  src/modeles/descriptionService.js
  test/modeles/descriptionService.spec.js
Labels: enhancement

#1545 [NIVEAU DE SÉCURITÉ] Ajoute une route permettant d'obtenir le niveau minimal de sécurité
  src/routes/connecte/routesConnecteApiService.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1546 [CORRECTION] Empêche le bouton de suppression de "voler" le focus dans les points d'accès de DÉCRIRE
  src/vues/fragments/elementsAjoutables/elementsAjoutables.pug
Labels: bug

#1548 [CORRECTION] Supprime tous les caractères spéciaux dans le nom de fichier
  src/routes/connecte/routesConnectePageService.js
  test/routes/connecte/routesConnectePageService.spec.js
Labels: bug

#1550 Ajoute les niveaux de sécurité minimal et choisi à l'évènement de journal complétude service
  src/modeles/journalMSS/evenementCompletudeServiceModifiee.js
  test/constructeurs/constructeurDescriptionService.js
  test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js
Labels: enhancement

#1551 Utilise le niveau de sécurité dans les règles de personnalisation
  donneesReferentiel.js
Labels: enhancement

#1554 Met à jour le package `express-ipfilter`
  package-lock.json
  package.json
Labels: dependencies

#1558 Met à jour la version de `express`
  package-lock.json
Labels: dependencies

#1559 Met à jour la version de `bcrypt`
  package-lock.json
Labels: dependencies

#1563 [CORRECTION] Force le tableau des mesures à 100% de la largeur
  public/assets/styles/homologation/mesures.css
Labels: bug

#1566 [CORRECTION] Erreur spécifique si le nom du service existe déjà lors de la modification d'un service
  src/routes/connecte/routesConnecteApiService.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: bug

#1568 Remplace les `GIF` de la visite guidée
  public/assets/images/visiteGuidee/contributeurs.gif
  public/assets/images/visiteGuidee/decrire.gif
  public/assets/images/visiteGuidee/homologuer.gif
  public/assets/images/visiteGuidee/indice_cyber.gif
  public/assets/images/visiteGuidee/pdf.gif
  public/assets/images/visiteGuidee/securiser.gif
  public/assets/images/visiteGuidee/tableau_de_bord.gif
Labels: enhancement

#1571 Logue la réponse de Brevo en cas d'erreur
  src/adaptateurs/adaptateurMailSendinblue.js
Labels: enhancement
