Repository betagouv/mon-service-securise, pull requests merged in 2024-09, with the labels that each got.

#1762 [CORRECTION] Répare le problème d’alignement pour les libellés longs dans les filtres
  svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
Labels: bug

#1761 [HISTORIQUE] Ajoute une notification de nouveauté pour les activités
  donneesReferentiel.js
  public/assets/images/notifications/illustrations/activites.png
Labels: enhancement

#1758 correction de l'orthographe d'un terme
  src/vues/service/indiceCyber.pug
Labels: enhancement

#1764 Utilise un séparateur ";" dans les CSV
  src/adaptateurs/adaptateurCsv.js
Labels: bug

#1765 Ajout d'un accent sur un mot
  svelte/lib/mesure/contenus/ContenuOngletPlanAction.svelte
Labels: enhancement

#1766 [CORRECTION] Affiche correctement le contenu des tiroirs
  public/assets/styles/tiroir.css
Labels: bug

#1771 Manipule directement `X-Forwarded-For` pour extraire les adresses IP
  src/adaptateurs/adaptateurGestionErreurSentry.js
  src/adaptateurs/adaptateurProtection.js
  src/http/middleware.js
  src/http/requeteHttp.js
  test/http/requeteHttp.spec.js
Labels: enhancement

#1775 [SOIN] Supprime les méthodes de mise à jour de mesures spécifiques en lot
  src/bus/cablage.js
  src/bus/evenementMesuresServiceModifiees.js
  src/depotDonnees.js
  src/depots/depotDonneesServices.js
  src/modeles/mesures.js
  src/modeles/service.js
  src/routes/connecte/routesConnecteApiService.js
  test/bus/evenementMesuresServiceModifiees.spec.js
  test/depots/depotDonneesServices.spec.js
  test/modeles/service.spec.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: code

#1776 [HISTORIQUE] Envoi un événement au bus lorsqu’une mesure spécifique est supprimée
  src/bus/cablage.js
  src/bus/evenementMesureServiceSupprimee.js
  src/depotDonnees.js
  src/depots/depotDonneesServices.js
  src/routes/connecte/routesConnecteApiService.js
  test/depots/depotDonneesServices.spec.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1777 Ajoute une étape de visite guidée pour les activités
  public/assets/images/visiteGuidee/securiser_activites.gif
  public/modules/tableauDeBord/actions/ActionMesure.mjs
  public/service/mesures.js
  svelte/lib/mesure/Mesure.svelte
  svelte/lib/mesure/contenus/ContenuOngletActivite.svelte
  svelte/lib/mesure/modeVisiteGuidee/donneesVisiteGuidee.ts
  svelte/lib/visiteGuidee/etapes/securiser/EtapeSecuriser.svelte
Labels: enhancement

#1778 [BLOG] Affiche les filtres de catégories sur l'intégralité de la ligne
  svelte/lib/blog/Blog.svelte
Labels: enhancement

#1780 Permet d’ajouter un nouveau propriétaire à un service
  consoleAdministration.js
Labels: enhancement

#1793 [CORRECTION] Télécharge les PDF avec une query string empêchant la mise en cache
  public/modules/tableauDeBord/actions/ActionTelechargement.mjs
Labels: bug

#1799 [AGENT CONNECT] Supprime l'utilisateur authentifié au début du parcours de connexion
  src/mss.js
  src/routes/nonConnecte/routesNonConnecteOidc.js
  test/routes/nonConnecte/routesNonConnecteOidc.spec.js
Labels: enhancement

#1800 [AGENT CONNECT] Redirige vers l'url demandée intialement après connexion
  public/apresAuthentification.js
  src/routes/nonConnecte/routesNonConnecteOidc.js
  src/vues/apresAuthentification.pug
  test/routes/nonConnecte/routesNonConnecteOidc.spec.js
Labels: enhancement

#1808 [CORRECTION] Fais pointer vers `cyber.gouv.fr`
  src/vues/aPropos.pug
  src/vues/cgu.pug
  src/vues/mss.pug
Labels: bug

#1809 Ajoute une action de déploiement vers un environnement de "DEV" dédié
  .github/workflows/deploiement-dev.yml
Labels: CI/CD

#1811 Limite la création de workflow "déploiement en env de DEV" au déclenchement manuel
  .github/workflows/deploiement-dev.yml
Labels: CI/CD

#1812 Empêche que l'appui sur `Entrée` dans la sélection de mention publie le commentaire
  svelte/lib/mesure/commentaire/CommentaireMesure.svelte
Labels: enhancement

#1814 Loggue les informations de l’exception levée après l’authentification
  src/routes/nonConnecte/routesNonConnecteOidc.js
Labels: enhancement

#1815 [SOIN] Supprime les avertissement dans eslint et dans le navigateur
  svelte/lib/mesure/contenus/activites/Activite.svelte
  svelte/lib/mesure/contenus/activites/ActiviteAjoutEcheance.svelte
  svelte/lib/mesure/contenus/activites/ActiviteAjoutPriorite.svelte
  svelte/lib/mesure/contenus/activites/ActiviteAjoutResponsable.svelte
  svelte/lib/mesure/contenus/activites/ActiviteAjoutStatut.svelte
  svelte/lib/mesure/contenus/activites/ActiviteMiseAJourEcheance.svelte
  svelte/lib/mesure/contenus/activites/ActiviteMiseAJourPriorite.svelte
  svelte/lib/mesure/contenus/activites/ActiviteMiseAJourStatut.svelte
  svelte/lib/mesure/contenus/activites/ActiviteSuppressionEcheance.svelte
  svelte/lib/mesure/contenus/activites/ActiviteSuppressionResponsable.svelte
  svelte/lib/mesure/contenus/activites/visualisation.ts
Labels: code

#1816 [CORRECTION] Ajoute un `nonce` sur la visite guidée de la page SÉCURISER
  src/routes/connecte/routesConnectePage.js
Labels: bug

#1817 [INFRASTRUTURE] Utilise un `pool` minimum de 0
  knexfile.js
Labels: bug, enhancement

#1820 [CORRECTION] Utilise un `pool` minimum de 0 pour le journal
  src/adaptateurs/adaptateurJournalMSSPostgres.js
Labels: bug, enhancement

#1821 [CORRECTION] Supprime le sélecteur CSS superflu
  src/pdf/modeles/ressources/styles.css
Labels: bug

#1822 [CORRECTION] Redirige correctement après connexion OIDC
  server.js
  src/mss.js
  src/routes/nonConnecte/routesNonConnecteOidc.js
  test/routes/nonConnecte/routesNonConnecteOidc.spec.js
  test/routes/testeurMSS.js
Labels: bug

#1823 [CORRECTION] N'ajoute pas d'URL de redirection si aucune n'est spécifiée
  src/routes/nonConnecte/routesNonConnecteOidc.js
  test/routes/nonConnecte/routesNonConnecteOidc.spec.js
Labels: bug

#1825 [CORRECTION] N'effectue pas d'appel API pour compléter les informations de l'entité
  src/depots/depotDonneesUtilisateurs.js
  test/depots/depotDonneesUtilisateurs.spec.js
Labels: bug

#1831 Ajoute une route pour mettre à jour un risque général de manière unitaire
  src/routes/connecte/routesConnecteApiService.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1832 Mets à jour le référentiel des risques
  donneesReferentiel.js
Labels: enhancement

#1837 Remplace les liens en `.ssi` par `.cyber`
  LICENSE
  README.md
Labels: enhancement

#1838 Remplace le tampon d'homologation
  public/assets/images/tamponHomologation.png
Labels: bug
