Repository betagouv/mon-service-securise, pull requests merged in 2024-02, with the labels that each got.

#1321 [SOIN] Ajoute un test pour vérifier que le bus ne crash pas s'il n'a pas de handlers
  test/bus/busEvenements.spec.js
Labels: code

#1324 [CORRECTION] Incrémente le `z-index` du menu flottant de tri des contributeurs
  public/assets/styles/tableauDeBord.css
Labels: bug

#1329 [CORRECTION] Passe le `bus` au `depotDonneesAutorisations`
  src/depotDonnees.js
Labels: bug

#1330 [CORRECTION] Ajoute le `await` manquant
  src/depots/depotDonneesHomologations.js
Labels: bug

#1332 [SÉCURISER] Ajoute des `container-queries` sur les indicateurs de la barre d'outils
  public/assets/styles/homologation/mesures.css
Labels: enhancement

#1334 [ADMIN] Répare la génération d'événements de complétude pour tous les services
  consoleAdministration.js
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
Labels: bug, code

#1335 [CORRECTION] Place `genereParAdministrateur` dans les `donnees`
  consoleAdministration.js
Labels: bug

#1338 [SÉCURITÉ] Ajoute un filtrage d'IP
  .env.template
  package-lock.json
  package.json
  src/adaptateurs/adaptateurEnvironnement.js
  src/adaptateurs/adaptateurGestionErreurSentry.js
  src/adaptateurs/adaptateurGestionErreurVide.js
  src/http/middleware.js
  src/mss.js
  test/mocks/middleware.js
  test/mss.spec.js
Labels: enhancement

#1342 Harmonise la hauteur du score indice cyber dans le tableau de bord
  public/assets/styles/tableauDeBord.css
Labels: enhancement

#1343 [CORRECTION] Ajoute un await sur les appels des méthodes `metsAJourTable` et `ajouteLigneDansTable`
  src/adaptateurs/adaptateurPostgres.js
Labels: bug

#1345 Ajoute un texte explicatif pour le nombre d'organisations
  public/assets/styles/formulaire.css
  src/vues/fragments/formulaireDescriptionService.pug
Labels: enhancement

#1349 [CORRECTION] Affiche correctement les éléments de connexion au format mobile
  public/assets/styles/entete.responsive.css
Labels: bug, enhancement

#1356 [CORRECTION] Répare l'injection de dépendances de l'adaptateur chiffrement
  consoleAdministration.js
  creeUtilisateurDemo.js
Labels: bug

#1361 Modifie le seuil à partir duquel on masque les indicateurs
  public/assets/styles/homologation/mesures.css
Labels: bug, enhancement

#1362 N'affiche plus le tampon d'homologation
  src/vues/service/dossiers.pug
Labels: enhancement

#1363 [TDB] Affiche un texte spécifique s'il n'y a pas de service
  public/modules/tableauDeBord/tableauDesServices.mjs
Labels: enhancement
