Repository betagouv/mon-service-securise, pull requests merged in 2024-03, with the labels that each got.

#1371 [CORRECTION] Bordure des "ronds" de pagination du carrousel
  public/assets/styles/nouvellesFonctionnalites/modaleNouvellesFonctionnalites.css
Labels: bug

#1370 [DECRIRE] Ajout de propriétés complementaires dans l'événement `EvenementCompletudeServiceModifiee`
  src/modeles/journalMSS/evenementCompletudeServiceModifiee.js
  test/constructeurs/constructeurService.js
  test/modeles/journalMSS/evenementCompletudeServiceModifiee.spec.js
Labels: enhancement

#1377 [SOIN] Supprime des données utilisateur inutiles
  public/modules/tableauDeBord/tableauDesServices.mjs
  src/modeles/utilisateur.js
  src/routes/privees/routesApiPrivee.js
  src/routes/publiques/routesApiPublique.js
  test/modeles/utilisateur.spec.js
  test/routes/privees/routesApiPrivee.spec.js
  test/routes/publiques/routesApiPublique.spec.js
Labels: code

#1379 Supprime l'utilisation de `x-real-ip`
  src/adaptateurs/adaptateurProtection.js
Labels: bug

#1383 Tri les dossiers archives dans l'ordre décroissant des date de prochaine homologation
  src/modeles/dossiers.js
  test/modeles/dossiers.spec.js
Labels: enhancement

#1385 Renomme "cartouche" en "encart" pour le tampon d'homologation
  public/modules/tableauDeBord/actions/ActionTelechargementTamponHomologation.js
  src/adaptateurs/adaptateurPdf.configurationTamponHomologation.js
  src/adaptateurs/adaptateurPdf.js
  src/vues/service/dossiers.pug
  src/vues/tiroirs/tiroirTelechargementTamponHomologation.pug
Labels: enhancement

#1390 [CORRECTION] Diminue la taille de police du footer
  public/assets/styles/piedPage.css
Labels: bug

#1389 Ajout de fonctionnalités dans l'historique du produit
  src/vues/historiqueProduit.pug
Labels: enhancement
