Repository betagouv/mon-service-securise, pull requests merged in 2024-01, with the labels that each got.

#1227 Renomme le bouton "Ajouter"
  svelte/lib/tableauDesMesures/TableauDesMesures.svelte
Labels: enhancement

#1228 Renomme les mesures "Ajoutée" et "Nouvelle" en "Spécifique"
  svelte/lib/mesure/mesure.store.ts
  svelte/lib/tableauDesMesures/TableauDesMesures.svelte
Labels: enhancement

#1232 [SECURISER] Ajoute une route pour obtenir l'indice cyber d'un service
  src/routes/privees/routesApiService.js
  test/routes/privees/routesApiService.spec.js
Labels: enhancement

#1237 [SECURISER] Modifie le wording de "Spécifique" en "Mesure ajoutées"
  svelte/lib/ui/CartoucheReferentiel.svelte
Labels: enhancement

#1234 [SECURISER] Ajoute une route pour obtenir le pourcentage de complétude des mesures d'un service
  src/routes/privees/routesApiService.js
  test/routes/privees/routesApiService.spec.js
Labels: enhancement

#1239 [CORRECTION] Corrige le wording "Non renseigné"
  svelte/lib/mesure/Mesure.svelte
Labels: bug

#1243 Cesse de loguer les erreurs `Navigation` dans Sentry
  src/adaptateurs/adaptateurProtection.js
Labels: code

#1248 [CORRECTION] Reinitialise la mesure par défaut au moment de l'instanciation du bundle
  svelte/lib/mesure/mesure.store.ts
Labels: bug

#1246 [SECURISER] Remplace la vue `mesure` par `mesure-v2`
  src/routes/privees/routesService.js
Labels: enhancement

#1249 [CORRECITON] Corrige l'alignement des indicateurs
  public/assets/styles/homologation/mesures.css
Labels: bug

#1251 Update CartoucheIndispensable.svelte
  svelte/lib/ui/CartoucheIndispensable.svelte
Labels: enhancement

#1254 Update mssConnecte.pug
  src/vues/mssConnecte.pug
Labels: enhancement

#1255 [SECURISER] Ajoute le chevron sur la ligne de mesure
  svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
Labels: enhancement

#1257 [CORRECTION] Conserve le markup HTML
  svelte/lib/directives/surligneTexte.ts
  svelte/lib/mesure/Mesure.svelte
  svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
Labels: bug

#1258 [CORRECTION] Corrige la recherche dans les descriptions longue
  svelte/lib/mesure/Mesure.svelte
  svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
Labels: bug

#1260 [CORRECTION] Corrige la sauvegarde des mesures sur Chrome
  svelte/lib/tableauDesMesures/TableauDesMesures.svelte
  svelte/lib/tableauDesMesures/ligne/LigneMesure.svelte
  svelte/lib/tableauDesMesures/tableauDesMesures.store.ts
  svelte/lib/ui/SelectionStatut.svelte
Labels: bug

#1261 [ACCESSIBILITE] Ajoute un titre sur toutes les pages de MSS
  src/vues/aPropos.pug
  src/vues/accessibilite.pug
  src/vues/activation.pug
  src/vues/base.pug
  src/vues/cgu.pug
  src/vues/confidentialite.pug
  src/vues/connexion.pug
  src/vues/erreur.pug
  src/vues/erreurAccesRefuse.pug
  src/vues/erreurTropDeTrafic.pug
  src/vues/historiqueProduit.pug
  src/vues/inscription.pug
  src/vues/mentionsLegales.pug
  src/vues/motDePasse/edition.pug
  src/vues/reinitialisationMotDePasse.pug
  src/vues/service/decrire.pug
  src/vues/service/dossiers.pug
  src/vues/service/formulaireEtapier.pug
  src/vues/service/indiceCyber.pug
  src/vues/service/mesures.pug
  src/vues/service/risques.pug
  src/vues/service/rolesResponsabilites.pug
  src/vues/statistiques.pug
  src/vues/tableauDeBord.pug
  src/vues/utilisateur/edition.pug
Labels: enhancement

#1262 [CORRECTION] Corrige l'alignement des légendes de filtre dans chrome
  svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
Labels: bug

#1266 [CORRECTION] Permets le décochage complet des filtres "ANSSI"
  svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
  svelte/lib/tableauDesMesures/tableauDesMesures.store.ts
Labels: bug

#1265 Modifie le wording des `placeholder` de recherche
  src/vues/tableauDeBord.pug
  svelte/lib/tableauDesMesures/TableauDesMesures.svelte
Labels: enhancement

#1264 [CORRECTION] Ajoute un paramètre pour positionner le menu flottant à la demande
  svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
  svelte/lib/ui/MenuFlottant.svelte
Labels: bug

#1270 [DECRIRE] Ajoute un titre de page sur la création de service
  src/vues/service/creation.pug
Labels: enhancement

#1269 Scroll sur le champ erroné au moment de la validation
  public/modules/interactions/validation.mjs
  test_public/modules/soumetsHomologation.spec.mjs
Labels: enhancement

#1272 Update reinitialisationMotDePasse.pug
  src/vues/reinitialisationMotDePasse.pug
Labels: enhancement

#1275 Ajoute des titres de pages spécifiques pour les étapes de l'homologation
  src/vues/service/dossiers.pug
  src/vues/service/etapeDossier/autorite.pug
  src/vues/service/etapeDossier/avis.pug
  src/vues/service/etapeDossier/dateTelechargement.pug
  src/vues/service/etapeDossier/decision.pug
  src/vues/service/etapeDossier/documents.pug
  src/vues/service/etapeDossier/recapitulatif.pug
  src/vues/service/formulaireEtapier.pug
Labels: enhancement

#1276 Modifie le wording du placeholder d'invitation de contributeur
  svelte/lib/gestionContributeurs/kit/ChampAvecSuggestions.svelte
Labels: enhancement

#1279 Ouvre les liens du BOM dans un nouvel onglet
  src/vues/mss.pug
  src/vues/mssConnecte.pug
Labels: enhancement

#1283 [CORRECTION] Espacement du bouton de profil
  public/assets/styles/entete.css
Labels: enhancement

#1285 [CORRECTION] Ajoute un "padding" minimum pour les petits écrans
  public/assets/styles/homologation/mesures.css
Labels: enhancement

#1286 [CORRECTION] Filtre les mesures en fonction de leur référentiel
  svelte/lib/tableauDesMesures/tableauDesMesures.store.ts
Labels: bug

#1284 Update donneesReferentiel.js
  donneesReferentiel.js
Labels: enhancement

#1287 [CORRECTION] Ajoute l'espace de `margin` du tableau des mesures à la `width`
  public/assets/styles/homologation/mesures.css
Labels: bug

#1291 [SOIN] Route /token en `async/await`
  src/routes/publiques/routesApiPublique.js
Labels: code

#1294 Ajoute l'affichage conditonnel des référentiels dans la page indice cyber
  src/routes/privees/routesService.js
  src/vues/service/indiceCyber.pug
Labels: enhancement

#1290 Ne masque pas les "sous-catégories" indispensable et recommandée du référentiel ANSSI
  svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
Labels: enhancement

#1292 [SENTRY] Modifie la requête pour supprimer les informations sensibles
  src/adaptateurs/adaptateurGestionErreurSentry.js
  src/mss.js
Labels: enhancement

#1298 Corrections de typo dans le référentiel
  donneesReferentiel.js
Labels: bug

#1301 Ajoute des `<p>` pour aérer les descriptions
  donneesReferentiel.js
Labels: enhancement

#1302 Corrige l'affichage du menu
  public/assets/styles/entete.css
Labels: enhancement

#1304 Améliore les performances de l'enregistrement des mesures générales
  src/depots/depotDonneesHomologations.js
Labels: enhancement

#1309 [CORRECTION] Cesse de planter si l'exception n'a pas de `response`
  src/adaptateurs/adaptateurTrackingSendinblue.js
Labels: bug

#1307 [SOINS] Passe des tests en `async/await`
  test/routes/privees/routesApiService.spec.js
Labels: code

#1308 Convertis le `button` de téléchargement en lien pour l'export des services
  public/modules/tableauDeBord/actions/ActionExport.mjs
  public/modules/tableauDeBord/gestionnaireEvenements.mjs
  src/vues/tiroirs/tiroirExport.pug
Labels: enhancement

#1310 [WORDING] Suppression d'un point dans le descriptif d'une mesure
  donneesReferentiel.js
Labels: enhancement

#1311 [WORDING] Suppression d'une coquille dans la description d'une mesure
  donneesReferentiel.js
Labels: enhancement

#1312 [TDB] Ajoute un lien cliquable pour l'indice cyber
  public/assets/styles/tableauDeBord.css
  public/modules/tableauDeBord/tableauDesServices.mjs
Labels: enhancement

#1315 [CORRECTION] Conditionne la boucle `forEach`
  src/bus/busEvenements.js
Labels: bug

#1316 [CORRECTION] Aligne correctement la `checkbox` d'inscription
  public/assets/styles/formulaire.css
Labels: enhancement

#1317 Ajoute `bold` sur les `nouvel-item` pour harmoniser MSS
  public/assets/styles/formulaire.css
Labels: enhancement

#1318 Modifie le wording de la description de l'indice cyber
  src/vues/service/indiceCyber.pug
Labels: enhancement

#1319 [DECRIRE] Supprime le sous-titre de la page
  src/vues/fragments/formulaireDescriptionService.pug
Labels: enhancement
