Repository betagouv/mon-service-securise, pull requests merged in 2024-08, with the labels that each got.

#1652 [CORRECTION] Corrige le lien vers l’article SecNumCloud
  donneesReferentiel.js
Labels: bug

#1653 [CI/CD] Autorise les déploiements sans `simple fast-forward` de git
  .github/workflows/deploiement.yml
Labels: code

#1651 [CORRECTION] Affiche un toast de changement de statut de mesure uniquement lorsque le statut est bien modifié
  svelte/lib/mesure/Mesure.svelte
Labels: bug

#1654 [CI/CD] Ajoute le job de déploiement en PROD
  .github/workflows/deploiement.yml
Labels: CI/CD

#1657 Ajoute la possibilité de générer un PDF via `puppeteer.connect()`
  .env.template
  docker-compose.yml
  src/adaptateurs/adaptateurPdf.puppeteer.js
Labels: enhancement

#1658 Valide la priorité envoyée à l’API
  src/erreurs.js
  src/modeles/mesure.js
  src/modeles/mesureGenerale.js
  src/modeles/mesureSpecifique.js
  src/routes/connecte/routesConnecteApiService.js
  test/modeles/mesure.spec.js
  test/modeles/mesureGenerale.spec.js
  test/modeles/mesureSpecifique.spec.js
  test/modeles/objetsPDF/objetPDFAnnexeMesures.spec.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1659 [CI/CD] Autorise le redéploiement d'un même commit
  .github/workflows/deploiement.yml
Labels: CI/CD

#1661 [SOIN] Soins de renommage du dépôt homologation
  src/depots/depotDonneesHomologations.js
Labels: code

#1660 [SOIN] Renomme `homologation` en `service`
  src/routes/connecte/routesConnecteApiServicePdf.js
Labels: code

#1664 [SOIN] Supprime la méthode `homologation` de la persistance
  src/adaptateurs/adaptateurPersistanceMemoire.js
  src/adaptateurs/adaptateurPostgres.js
  src/depots/depotDonneesHomologations.js
  test/depots/depotDonneesHomologations.spec.js
  test/depots/depotDonneesServices.spec.js
Labels: code

#1663 [SOIN] Supprime un middleware non utilisé
  server.js
  src/http/middleware.js
  test/http/middleware.spec.js
  test/mocks/middleware.js
Labels: code

#1667 [SOIN] Middleware en `async/await` et `early return`
  src/http/middleware.js
Labels: code

#1675 Déclenche la vraie tâche à mettre en CRON
  clevercloud/cron.json
Labels: code

#1678 Utilise un script shell pour avoir accès aux variables d'environnement
  clevercloud/cron.json
  scripts/taches/tacheEnvoieMailsNotificationExpiration.sh
Labels: code

#1683 [CORRECTION] Exécute correctement le script
  clevercloud/cron.json
Labels: bug, code

#1679 [SÉCURISER] Ajoute un titre au tiroir lors de l'ajout d'une mesure spécifique
  svelte/lib/tableauDesMesures/actionsTiroir.ts
Labels: enhancement

#1682 [PLAN D'ACTION] Ajoute l'échéance à la mesure
  src/erreurs.js
  src/modeles/mesure.js
  src/modeles/mesureGenerale.js
  src/modeles/mesureSpecifique.js
  src/routes/connecte/routesConnecteApiService.js
  test/modeles/mesure.spec.js
  test/modeles/mesureGenerale.spec.js
  test/modeles/mesureSpecifique.spec.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1685 [CORRECTION] Décode les "/" des échéances
  src/routes/connecte/routesConnecteApiService.js
  test/routes/connecte/routesConnecteApiService.spec.js
Labels: enhancement

#1691 [CORRECTION] Désactive le bouton "inscription"
  public/modules/interactions/brancheSoumissionFormulaireUtilisateur.js
Labels: bug

#1688 Met à jour le lien de blog sur l'homologation
  src/vues/service/etapeDossier/autorite.pug
Labels: enhancement

#1692 [CORRECTION] Utilise la variable `CONTAINER_VERSION`
  src/adaptateurs/adaptateurEnvironnement.js
Labels: bug

#1686 [CI/CD] Ajoute une étape d'invalidation du cache Baleen
  .github/workflows/deploiement.yml
Labels: CI/CD

#1700 Utilise du gris pour les vignettes de rôle inconnu
  public/assets/styles/palette.css
  svelte/lib/gestionContributeurs/kit/Initiales.svelte
Labels: enhancement

#1707 [CORRECTION] Fais fonctionner le bouton « Effacer » du date-picker
  svelte/lib/tableauDesMesures/ligne/SelectionEcheance.svelte
Labels: bug

#1711 [PLAN D'ACTION] Ajoute une notification de nouveauté pour le plan d'action
  donneesReferentiel.js
  public/assets/images/notifications/illustrations/prioritePlanAction.png
Labels: enhancement

#1712 [SOIN] Le dépôt données Utilisateur a le moins d’accroche possible avec la persistance
  src/depots/depotDonneesUtilisateurs.js
Labels: code

#1718 Modifie l'illustration de la notification du plan d'action
  public/assets/images/notifications/illustrations/prioritePlanAction.png
Labels: enhancement

#1720 [CORRECTION] Remplace le lien de la première nouveauté
  donneesReferentiel.js
Labels: bug

#1726 [CORRECTION] Supprime la bordure sur le sélecteur de priorité lorsqu'il est désactivé ET vide
  svelte/lib/ui/SelectionPriorite.svelte
Labels: enhancement

#1729 [CORRECTION] Ajoute l'adaptateur chiffrement dans le dépôt créé par la tâche d'envoi de mails
  src/depotDonnees.js
Labels: bug

#1731 [SOIN] Mutualise la gestion de la suppression des filtres
  svelte/lib/tableauDesMesures/TableauDesMesures.svelte
  svelte/lib/tableauDesMesures/aucunResultat/AucunResultat.svelte
  svelte/lib/tableauDesMesures/filtres/MenuFiltres.svelte
Labels: code

#1733 [CONSOLE ADMIN] Ajoute des utilitaires pour lire/déchiffrer des utilisateurs/services
  consoleAdministration.js
Labels: enhancement, code

#1736 [CORRECTION] Ne conserve pas les données modifiées de la mesure dans le tiroir
  svelte/lib/tableauDesMesures/TableauDesMesures.svelte
Labels: bug

#1737 Correction d'un mot
  svelte/lib/ui/SelectionResponsables.svelte
Labels: enhancement

#1739 [CORRECTION] Cible le titre de la mesure pour ouvrir le tiroir
  svelte/lib/visiteGuidee/etapes/securiser/EtapeSecuriser.svelte
Labels: bug

#1738 [CORRECTION] Corrige l’effacement d’une date d’échéance de mesure déjà définie
  svelte/lib/ui/SelectionEcheance.svelte
Labels: bug

#1745 [HISTORIQUE] Enregistre les changements de priorité des mesures
  src/bus/abonnements/consigneActiviteMesure.js
  test/bus/abonnements/consigneActiviteMesure.spec.js
Labels: enhancement

#1747 [HISTORIQUE] Gère le cas de l’ajout d’un statut
  src/bus/abonnements/consigneActiviteMesure.js
  test/bus/abonnements/consigneActiviteMesure.spec.js
Labels: enhancement

#1753 [CI/CD] N'installe pas Chromium dans la CI de github
  .github/workflows/node.js.yml
Labels: CI/CD

#1757 [CORRECTION] Affiche correctement l'indice cyber personnalisé
  src/pdf/modeles/indiceCyberPersonnalise/scoreIndiceCyberPersonnalise.pug
Labels: bug
