Repository betagouv/mon-service-securise, pull requests merged in 2025-02, with the labels that each got.

#2049 Améliore le README
  README.md
Labels: enhancement

#2053 Modifie le "GIF" de présentation du tableau de bord
  public/assets/images/visiteGuidee/tableau_de_bord.gif
  svelte/lib/visiteGuidee/etapes/piloter/EtapePiloter.svelte
Labels: enhancement

#2054 Utilise la fonction `captureCheckIn` afin de monitorer correctement l'exécution de la tâche
  scripts/taches/tacheEnvoieMailsNotificationExpiration.js
Labels: enhancement

#2062 Change le wording hébergement
  src/vues/securite.pug
Labels: enhancement

#2063 Supprime l'encart de stat sur l'évolution de l'IC à 1 an
  src/vues/statistiques.pug
Labels: enhancement

#2064 Contraint le cartouche référentiel à rester sur une ligne
  svelte/lib/ui/CartoucheReferentiel.svelte
Labels: enhancement

#2059 [CHIFFREMENT] Supprime l'adaptateur "Vault"
  .env.template
  consoleAdministration.js
  docker-compose.yml
  scripts/chiffrage/dechiffreService.sh
  scripts/chiffrage/dechiffreUtilisateur.sh
  scripts/init-mss-crypto.sh
  src/adaptateurs/adaptateurChiffrementVault.js
  src/adaptateurs/adaptateurEnvironnement.js
  test/creeUtilisateurDemo.spec.js
Labels: code

#2066 Corrige le wording de la page de maintenance
  src/vues/maintenance.pug
Labels: enhancement

#2065 Ajoute la mention de "Cloud temple" pour Clever Cloud
  src/vues/aPropos.pug
Labels: enhancement

#2069 Empêche le bouton du tampon d'homologation de passer sur 2 lignes
  public/assets/styles/dossiers.css
Labels: bug

#2076 Interdis la mise en cache par défaut
  src/http/middleware.js
  src/mss.ts
  test/http/middleware.spec.js
  test/mocks/middleware.js
Labels: enhancement

#2074 [SOIN] Supprime les fichiers spécifiques à Scalingo
  .buildpacks
  Aptfile
  Procfile
  cron.json
Labels: code

#2073 [SOIN] Supprime l'affichage des commentaires dans le pug
  src/vues/fragments/composantSvelte.pug
Labels: code

#2077 Affiche l'avancement des modifications des `evenements` du journal
  migrationHash.js
Labels: enhancement

#2078 [CORRECTION] Corrige les paramètres de l'envoi de notification d'expiration
  src/adaptateurs/adaptateurMailSendinblue.js
Labels: bug

#2075 [SOIN] Variabilise le pool de connexion maximum pour Postgres
  .env.template
  knexfile.js
  migrationHash.js
  src/adaptateurs/adaptateurEnvironnement.js
  src/adaptateurs/adaptateurJournalMSSPostgres.js
  src/adaptateurs/adaptateurSupervisionMetabase.js
Labels: enhancement, code
