Repository betagouv/mon-service-securise, pull requests merged in 2025-04, with the labels that each got.

#2118 Modifie le wording de la doctrine d'homologation
  svelte/lib/doctrineHomologation/DoctrineHomologation.svelte
Labels: enhancement

#2116 [CORRECTION] Ne permet pas de réinitialiser un mot de passe pour les utilisateurs "Pro Connecté"
  src/depots/depotDonneesUtilisateurs.js
  test/depots/depotDonneesUtilisateurs.spec.js
Labels: bug, enhancement

#2126 Met à jour la version de l'UI Kit
  src/vues/mss.pug
Labels: enhancement

#2132 Ajoute la statistique du "taux de satisfaction"
  public/assets/images/satisfaction.svg
  src/vues/statistiques.pug
Labels: enhancement

#2133 [CORRECTION] Coupe le nom du service s'il ne tient pas sur une ligne
  src/pdf/modeles/ressources/styles.css
Labels: bug

#2137 Ajoute un "ZeroWidthSpace" sur le nom du service
  src/pdf/modeles/tamponHomologation.pug
Labels: enhancement

#2139 [CORRECTION] Place le bandeau d'enregistrement en arrière-plan
  public/assets/styles/homologation/formulaire.css
Labels: bug

#2138 [CORRECTION] Gère correctement les invités avec MPA
  src/routes/nonConnecte/routesNonConnecteOidc.js
  test/routes/nonConnecte/routesNonConnecteOidc.spec.js
Labels: bug

#2145 Modification du wording du bloc "communauté" de la home
  src/vues/home.pug
Labels: enhancement

#2151 [CORRECTION] Utilise l'email des informations ProConnect
  src/utilisateur/serviceApresAuthentification.js
  test/utilisateur/serviceApresAuthentification.spec.js
Labels: bug

#2146 Compile le code avant de tenter de l'utiliser
  package.json
Labels: bug

#2159 [CORRECTION] Conserve le statut "indispensable" d'une mesure
  src/moteurRegles.js
  test/moteurRegles.spec.js
Labels: bug

#2157 [CORRECTION] Ne tente pas de mettre à jour MPA si le profil de l'utilisateur n'est pas complet
  src/depots/depotDonneesUtilisateurs.js
  test/depots/depotDonneesUtilisateurs.spec.js
Labels: bug

#2160 [CORRECTION] Renvoi une erreur 429 en cas de "rate-limit" dépassé.
  src/adaptateurs/adaptateurProtection.js
  src/vues/erreurTropDeTrafic.pug
Labels: bug, enhancement
