Repository betagouv/mon-service-securise, pull requests merged in 2025-05, with the labels that each got.

#2164 [CORRECTION] Filtre les profils qui n'ont pas une entité complète
  admin/consoleAdministration.js
Labels: bug

#2174 Remonte le tiroir `Svelte` au-dessus du centre d'aide
  svelte/lib/tiroir/Tiroir.svelte
Labels: bug, enhancement

#2175 Met à jour la version de `xlsx`
  package-lock.json
  package.json
Labels: enhancement, dependencies

#2176 Modifie le wording du bouton de webinaire
  src/vues/home.pug
Labels: Wording
