Repository betagouv/mon-service-securise, pull requests merged in 2025-07, with the labels that each got.

#2232 [CORRECTION] Ne tente pas de créer un objet de Date si la chaine de caractère est vide
  svelte/lib/rapportTeleversement/composants/LigneService.svelte
Labels: bug

#2238 Ajoute la possibilité de fermeture des "Toast"
  svelte/lib/ui/Toast.svelte
  svelte/lib/ui/Toaster.svelte
  svelte/lib/ui/stores/toaster.store.ts
Labels: enhancement

#2244 Ajoute la propriété facultative de "Description longue" sur les mesures spécifiques
  src/modeles/mesureSpecifique.js
  tdd-todo/import_mesures_specifiques.md
  test/modeles/mesureSpecifique.spec.js
Labels: enhancement

#2262 [SOIN] Répare les scripts de démarrage et de test
  docker-compose.yml
  scripts/start.sh
  scripts/tests.sh
Labels: bug, dependencies, CI/CD
