Repository betagouv/mon-service-securise, pull requests merged in 2025-09, with the labels that each got.

#2357 Type la `Request` renvoyée par `valideBody`
  src/http/validePayloads.ts
  src/routes/connecte/routesConnecteApiBrouillonService.ts
Labels: code

#2368 [CORRECTION] Assigne `estComplete` en mode "réactif", afin de l'évaluer au montage
  svelte/lib/creationV2/etapes/etape1/QuestionStatutDeploiement.svelte
Labels: bug

#2376 Modifie le wording des questions
  svelte/lib/creationV2/etapes/etape1/QuestionNomService.svelte
  svelte/lib/creationV2/etapes/etape2/QuestionSpecificitesProjet.svelte
  svelte/lib/creationV2/etapes/toutesEtapes.ts
Labels: enhancement

#2381 Enlève l'obligation de remplissage pour les listes de champs texte côté front
  svelte/lib/creationV2/etapes/etape1/QuestionPointsAcces.svelte
  svelte/lib/creationV2/etapes/etape3/QuestionCategoriesDonneesTraitees.svelte
Labels: enhancement

#2383 Evite de sauter une question à cause d'une race condition
  svelte/lib/creationV2/CreationV2.svelte
Labels: enhancement
