Repository betagouv/mon-service-securise, pull requests merged in 2025-08, with the labels that each got.

#2283 [CORRECTIONS] Corrige l'affichage de la liste de mesures
  svelte/lib/listeMesures/ListeMesures.svelte
  svelte/lib/listeMesures/mesureSpecifique/TableauVideMesuresSpecifiques.svelte
  svelte/lib/ui/Tableau.svelte
  tdd-todo/import_mesures_specifiques.md
Labels: enhancement

#2284 Ajoute l'onglet "Toutes les mesures"
  svelte/lib/listeMesures/ListeMesures.svelte
  svelte/lib/ui/Tableau.svelte
  tdd-todo/import_mesures_specifiques.md
Labels: enhancement

#2307 Ajoute un champ d'édition pour la description longue d'une mesure spécifique
  svelte/lib/mesure/contenus/ContenuOngletMesure.svelte
  svelte/lib/mesure/mesure.store.ts
  svelte/lib/ui/DescriptionLongueMesure.svelte
  tdd-todo/import_mesures_specifiques.md
Labels: enhancement

#2331 [CORRECTION] N'essaie pas d'insérer si aucun modèle n'est passé
  src/adaptateurs/adaptateurPostgres.js
Labels: bug

#2333 [CORRECTION] Désactive le clic
  svelte/lib/listeMesures/ListeMesures.svelte
Labels: bug

#2343 Nettoie la configuration ESLint
  .eslintrc.js
Labels: code
