Repository betagouv/mon-service-securise, pull requests merged in 2025-03, with the labels that each got.

#2081 [CORRECTION] Vérifie si la réponse axios contient bien une payload
  public/scripts/csrf.mjs
Labels: bug

#2082 Ajoute la condition singulier/pluriel sur les cartes d'informations du tableau de bord
  svelte/lib/tableauDeBord/BandeauInfo.svelte
Labels: bug, enhancement

#2083 Passe l'identifiant d'erreur Sentry dans l'URL du support utilisateur
  src/vues/erreur.pug
Labels: enhancement

#2094 Ajoute une notification de nouveauté pour MesServicesCyber
  donneesReferentiel.js
  public/assets/images/notifications/illustrations/mesServicesCyber.png
Labels: enhancement

#2102 ⏳ Ajoute la suite cyber dans l'entête
  public/assets/styles/entete.responsive.css
  public/bibliotheques/lab-anssi-ui-kit-1.1.1.min.js
  src/vues/mss.pug
Labels: enhancement

#2105 Corrige l'affichage de la suite cyber sur la page de connexion
  public/assets/styles/mss.css
  src/vues/mss.pug
Labels: bug
