Repository betagouv/mon-service-securise, pull requests merged in 2025-01, with the labels that each got.

#1988 Change la formulation du sous-titre
  src/vues/service/mesures.pug
Labels: enhancement

#1989 [SÉCURISER] Permet d'appliquer la recherche textuelle sur les "précisions"
  svelte/lib/tableauDesMesures/stores/rechercheTextuelle.store.ts
Labels: enhancement

#1986 Augmentation des infos transmises à Sentry
  server.ts
  src/adaptateurs/adaptateurGestionErreurSentry.js
  src/adaptateurs/adaptateurGestionErreurVide.js
  src/http/middleware.js
  test/http/middleware.spec.js
Labels: enhancement, code

#1987 [SOIN] Enrichis les erreurs loguées par le bus
  src/bus/busEvenements.js
  src/erreurs.js
  test/bus/busEvenements.spec.js
Labels: documentation, code

#1990 [CORRECTION] Corrige l'enregistrement des mesures dans le cas où un problème survient lors de la récupération des activités
  svelte/lib/mesure/mesure.api.ts
Labels: enhancement

#1991 [TDB-V2] Applique les corrections d'affichage de la barre de recherche
  public/assets/images/ui-kit/suppression_champ.svg
  public/assets/styles/palette.css
  svelte/lib/ui/BarreDeRecherche.svelte
  svelte/lib/uiKit/UiKit.svelte
Labels: enhancement

#1993 [CORRECTION] Ajoute une espace au dessus des actions du tiroir de sup…
  public/assets/styles/tiroir.css
Labels: bug

#1994 [STATISTIQUES] Cesse d'afficher l'évolution
  src/vues/statistiques.pug
Labels: enhancement

#1996 [CORRECTION] Remplace le département lors de la sélection d'une organisation
  svelte/lib/inscription/SelectionDepartement.svelte
  svelte/lib/profil/Profil.svelte
Labels: bug, enhancement

#1995 [CORRECTION] Renvoi correctement les établissements "secondaires" lors d'une recherche par SIRET
  src/adaptateurs/adaptateurRechercheEntrepriseAPI.js
  test/adaptateurs/adaptateurRechercheEntrepriseAPI.spec.js
Labels: bug, enhancement

#1998 [CORRECTION] Retourne les infos du siège si le matching établissements est vide
  src/adaptateurs/adaptateurRechercheEntrepriseAPI.js
  test/adaptateurs/adaptateurRechercheEntrepriseAPI.spec.js
Labels: bug

#1999 Vérifie une hypothèse sur les erreurs CSRF
  src/routes/connecte/routesConnecteApi.js
  test/routes/connecte/routesConnecteApi.spec.js
Labels: enhancement

#2004 [CORRECTION] Décode le nom du service pour la confirmation de suppression
  svelte/lib/ui/tiroirs/TiroirSuppression.svelte
Labels: bug

#2008 [CORRECTION] Empêche l'etiquette du statut d'homologation de se propager sur plusieurs lignes
  svelte/lib/tableauDeBord/elementsDeService/EtiquetteHomologation.svelte
Labels: bug

#2010 Utilise la route de mise à jour de profil pour l’inscription
  src/adaptateurs/adaptateurProfilAnssi.js
  src/adaptateurs/adaptateurProfilAnssiVide.js
  src/depots/depotDonneesUtilisateurs.js
  test/depots/depotDonneesUtilisateurs.spec.js
Labels: enhancement

#2011 [CORRECTION] Ne prend pas en compte les services dont le statut d'homologation est masqué pour un utilisateur dans l'affichage des onglets
  svelte/lib/tableauDeBord/stores/affichageParStatutHomologation.ts
  svelte/lib/tableauDeBord/stores/affichageTableauVide.ts
  svelte/lib/tableauDeBord/tableauDeBord.d.ts
Labels: bug

#2024 [CORRECTION] Passe les labels de besoins de sécurité au pluriel
  svelte/lib/tableauDeBord/TableauDesServices.svelte
Labels: bug, enhancement

#2027 Ajoute des sélecteurs pour Matomo
  svelte/lib/tableauDeBord/TableauDesServices.svelte
  svelte/lib/tableauDeBord/elementsDeService/EtiquetteContributeurs.svelte
  svelte/lib/tableauDeBord/elementsDeService/EtiquetteHomologation.svelte
  svelte/lib/tableauDeBord/elementsDeService/EtiquetteIndiceCyber.svelte
Labels: enhancement, code

#2029 [TDB] Ajoute la barre "sticky" du tableau des services
  svelte/lib/tableauDeBord/BandeauFiltres.svelte
  svelte/lib/tableauDeBord/BandeauInfo.svelte
  svelte/lib/tableauDeBord/TableauDeBord.svelte
  svelte/lib/tableauDeBord/TableauDesServices.svelte
Labels: enhancement

#2030 [CORRECTION] "Échappe" le nom du service pour le `pattern` de confirmation de suppression
  svelte/lib/ui/tiroirs/TiroirSuppression.svelte
Labels: bug

#2032 Corrige une faute d'orthographe
  svelte/lib/tableauDeBord/BandeauInfo.svelte
Labels: bug

#2037 Ajoute une notification au centre de notifications
  donneesReferentiel.js
  public/assets/images/notifications/illustrations/tableauDeBordV2.png
Labels: enhancement

#2039 Attrape l'erreur lancée par `jwt.verify` afin d'être redirigé vers la page de login
  src/adaptateurs/adaptateurJWT.js
Labels: bug

#2020 [TDB] Ajoute un `hover` sur les lignes de service
  public/assets/images/tableauDeBord/icone_ouvrir_agrandir.svg
  svelte/lib/tableauDeBord/TableauDesServices.svelte
Labels: enhancement

#2042 [CORRECTION] Corrige l'affichage de la cellule nom du TDB
  svelte/lib/tableauDeBord/TableauDesServices.svelte
Labels: bug

#2043 [CORRECTION] Corrige la suppression d'utilisateur dans la console admin
  consoleAdministration.js
Labels: bug
